Repository cisagov/ScubaGear, pull requests merged in 2023-02, with the labels that each got.

#130 EXO 2.7 Rego Bug Fix | Only Enabled Correctly Configured Rules Pass
  Rego/EXOConfig.rego
  Testing/Unit/Rego/EXO/EXOConfig2_07_test.rego
Labels: bug

#146 Add Service Principal authentication via CertificateThumprint parameters and correct erroneous GCC High/DOD Defender endpoints
  PowerShell/ScubaGear/Modules/Connection/ConnectHelpers.psm1
  PowerShell/ScubaGear/Modules/Connection/Connection.psm1
  PowerShell/ScubaGear/Modules/Orchestrator.psm1
  PowerShell/ScubaGear/Modules/Providers/ExportDefenderProvider.psm1
  PowerShell/ScubaGear/Modules/Providers/ExportOneDriveProvider.psm1
  PowerShell/ScubaGear/Modules/Providers/ExportSharePointProvider.psm1
  PowerShell/ScubaGear/RequiredVersions.ps1
  Rego/OneDriveConfig.rego
  Rego/SharepointConfig.rego
  Testing/Unit/Rego/OneDrive/OneDriveConfig2_01_test.rego
Labels: bug, enhancement

#149 Fix wrong SPO GCC endpoint when using Service Principals
  PowerShell/ScubaGear/Modules/Connection/Connection.psm1
Labels: bug

#147 Add CAP html table to AAD report
  PowerShell/ScubaGear/Modules/CreateReport/CreateReport.psm1
  PowerShell/ScubaGear/Modules/CreateReport/IndividualReport/IndividualReport.html
  PowerShell/ScubaGear/Modules/CreateReport/ParentReport/ParentReport.html
  PowerShell/ScubaGear/Modules/CreateReport/images/angle-down-solid.svg
  PowerShell/ScubaGear/Modules/CreateReport/images/angle-right-solid.svg
  PowerShell/ScubaGear/Modules/CreateReport/images/cisa_logo.png
  PowerShell/ScubaGear/Modules/CreateReport/main.js
  PowerShell/ScubaGear/Modules/CreateReport/scripts/main.js
  PowerShell/ScubaGear/Modules/CreateReport/styles/ParentReportStyle.css
  PowerShell/ScubaGear/Modules/CreateReport/styles/main.css
  PowerShell/ScubaGear/Modules/Orchestrator.psm1
  PowerShell/ScubaGear/Modules/Providers/ExportAADProvider.psm1
  PowerShell/ScubaGear/Modules/Providers/ProviderHelpers/AADConditionalAccessHelper.psm1
  Rego/AADConfig.rego
  Testing/Unit/Pester/Providers/AADProvider/CapSnippets/AccessControls.json
  Testing/Unit/Pester/Providers/AADProvider/CapSnippets/Apps.json
  Testing/Unit/Pester/Providers/AADProvider/CapSnippets/Conditions.json
  Testing/Unit/Pester/Providers/AADProvider/CapSnippets/SessionControls.json
  Testing/Unit/Pester/Providers/AADProvider/CapSnippets/Users.json
  Testing/Unit/Pester/Providers/AADProvider/Export-Caps.Tests.ps1
  Testing/Unit/Rego/AAD/AADConfig2_01_test.rego
  Testing/Unit/Rego/AAD/AADConfig2_02_test.rego
  Testing/Unit/Rego/AAD/AADConfig2_03_test.rego
  Testing/Unit/Rego/AAD/AADConfig2_04_test.rego
  Testing/Unit/Rego/AAD/AADConfig2_09_test.rego
  Testing/Unit/Rego/AAD/AADConfig2_10_test.rego
  Testing/Unit/Rego/AAD/AADConfig2_13_test.rego
  Testing/Unit/Rego/AAD/AADConfig2_17_test.rego
Labels: enhancement

#122 Updated OneDrive 2.1, 2.2 and 2.3 policy
  Rego/OneDriveConfig.rego
  Testing/Unit/Rego/OneDrive/OneDriveConfig2_01_test.rego
  Testing/Unit/Rego/OneDrive/OneDriveConfig2_02_test.rego
  Testing/Unit/Rego/OneDrive/OneDriveConfig2_03_test.rego
Labels: bug
