Repository cisagov/ScubaGear, pull requests merged in 2023-12, with the labels that each got.

#695 Add -UseBasicParsing to Invoke-WebRequest to support Servercore Windows images
  PowerShell/ScubaGear/Modules/Providers/ExportEXOProvider.psm1
  PowerShell/ScubaGear/Modules/Providers/ExportPowerPlatformProvider.psm1
Labels: enhancement

#692 updated checkout action version
  .github/workflows/run_markdown_check.yaml
  .github/workflows/run_opa_tests.yaml
  .github/workflows/run_powershell_tests.yaml
  .github/workflows/run_psscriptanalyzer.yaml
  .github/workflows/run_release.yaml
  .github/workflows/run_smoke_test.yaml
Labels: enhancement

#641 Download OPA only when required & Print real error message
  OPA.ps1
  SetUp.ps1
Labels: enhancement

#631 Update unused function parameters with wildcard variables
  Rego/DefenderConfig.rego
  Rego/EXOConfig.rego
  Rego/PowerPlatformConfig.rego
  Rego/TeamsConfig.rego
  Rego/Utils/ReportUtils.rego
Labels: enhancement

#725 Remove PnP work-around for Smoke Test
  Testing/Functional/SmokeTest/SmokeTestUtils.ps1
Labels: bug

#721 Breaking dependency on opa in unit testing
  .github/workflows/run_powershell_tests.yaml
  PowerShell/ScubaGear/Modules/RunRego/RunRego.psm1
  Testing/Unit/PowerShell/RunRego/Run-Rego.Tests.ps1
Labels: enhancement

#682 add progress bar for OPA download
  OPA.ps1
Labels: enhancement

#659 Refactor Sharepoint Rego Code
  .regal/config.yaml
  CONTENTSTYLEGUIDE.md
  Rego/SharepointConfig.rego
  Testing/Unit/Rego/Sharepoint/SharepointConfig_01_test.rego
  Testing/Unit/Rego/Sharepoint/SharepointConfig_02_test.rego
  Testing/Unit/Rego/Sharepoint/SharepointConfig_03_test.rego
  Testing/Unit/Rego/Sharepoint/SharepointConfig_04_test.rego
Labels: enhancement

#727 Integrate OCC review feedback into the AAD baseline
  baselines/aad.md
Labels: baseline-document

#720 Integrate OCC review feedback into the Defender baseline
  baselines/defender.md
Labels: baseline-document

#719 Integrate OCC review feedback into the Power Bi baseline
  baselines/powerbi.md
Labels: baseline-document

#718 Integrate OCC review feedback into EXO baseline
  baselines/exo.md
Labels: baseline-document

#661 Refactor Power Platform
  Rego/PowerPlatformConfig.rego
  Testing/Unit/Rego/PowerPlatform/PowerPlatformConfig_01_test.rego
  Testing/Unit/Rego/PowerPlatform/PowerPlatformConfig_02_test.rego
  Testing/Unit/Rego/PowerPlatform/PowerPlatformConfig_03_test.rego
  Testing/Unit/Rego/PowerPlatform/PowerPlatformConfig_04_test.rego
  Testing/Unit/Rego/PowerPlatform/PowerPlatformConfig_05_test.rego
Labels: enhancement

#660 Refactor Teams Rego Code
  Rego/TeamsConfig.rego
  Testing/Unit/Rego/Teams/TeamsConfig_01_test.rego
  Testing/Unit/Rego/Teams/TeamsConfig_02_test.rego
  Testing/Unit/Rego/Teams/TeamsConfig_03_test.rego
  Testing/Unit/Rego/Teams/TeamsConfig_04_test.rego
  Testing/Unit/Rego/Teams/TeamsConfig_05_test.rego
  Testing/Unit/Rego/Teams/TeamsConfig_06_test.rego
  Testing/Unit/Rego/Teams/TeamsConfig_07_test.rego
  Testing/Unit/Rego/Teams/TeamsConfig_08_test.rego
Labels: enhancement

#722 Integrate OCC review feedback into the Teams baseline
  baselines/teams.md
Labels: baseline-document

#717 Integrate OCC review feedback into Power Platform baseline
  baselines/powerplatform.md
Labels: baseline-document

#723 Integrate OCC review feedback into the SharePoint/OneDrive baseline
  baselines/sharepoint.md
Labels: baseline-document

#728 Smoke test periodically fails
  Testing/Functional/SmokeTest/UpdateSelenium.ps1
Labels: enhancement

#664 Refactor AAD Rego Code
  Rego/AADConfig.rego
  Testing/Unit/Rego/AAD/AADConfig_01_test.rego
  Testing/Unit/Rego/AAD/AADConfig_02_test.rego
  Testing/Unit/Rego/AAD/AADConfig_03_test.rego
  Testing/Unit/Rego/AAD/AADConfig_04_test.rego
  Testing/Unit/Rego/AAD/AADConfig_05_test.rego
  Testing/Unit/Rego/AAD/AADConfig_06_test.rego
  Testing/Unit/Rego/AAD/AADConfig_07_test.rego
  Testing/Unit/Rego/AAD/AADConfig_08_test.rego
Labels: enhancement

#663 Refactor Defender Rego Code
  Rego/DefenderConfig.rego
  Testing/Unit/Rego/Defender/DefenderConfig_01_test.rego
  Testing/Unit/Rego/Defender/DefenderConfig_02_test.rego
  Testing/Unit/Rego/Defender/DefenderConfig_03_test.rego
  Testing/Unit/Rego/Defender/DefenderConfig_04_test.rego
  Testing/Unit/Rego/Defender/DefenderConfig_05_test.rego
  Testing/Unit/Rego/Defender/DefenderConfig_06_test.rego
Labels: enhancement

#662 Refactor Exo Rego Code
  Rego/EXOConfig.rego
  Testing/Unit/Rego/EXO/EXOConfig_01_test.rego
  Testing/Unit/Rego/EXO/EXOConfig_02_test.rego
  Testing/Unit/Rego/EXO/EXOConfig_03_test.rego
  Testing/Unit/Rego/EXO/EXOConfig_04_test.rego
  Testing/Unit/Rego/EXO/EXOConfig_05_test.rego
  Testing/Unit/Rego/EXO/EXOConfig_06_test.rego
  Testing/Unit/Rego/EXO/EXOConfig_07_test.rego
  Testing/Unit/Rego/EXO/EXOConfig_08_test.rego
  Testing/Unit/Rego/EXO/EXOConfig_09_test.rego
  Testing/Unit/Rego/EXO/EXOConfig_10_test.rego
  Testing/Unit/Rego/EXO/EXOConfig_11_test.rego
  Testing/Unit/Rego/EXO/EXOConfig_12_test.rego
  Testing/Unit/Rego/EXO/EXOConfig_13_test.rego
  Testing/Unit/Rego/EXO/EXOConfig_14_test.rego
  Testing/Unit/Rego/EXO/EXOConfig_15_test.rego
  Testing/Unit/Rego/EXO/EXOConfig_16_test.rego
  Testing/Unit/Rego/EXO/EXOConfig_17_test.rego
Labels: enhancement

#744 Add PowerShell and YAML linters
  .github/workflows/run_linter_powershell.yaml
  .github/workflows/run_linter_yaml.yaml
  Testing/Linting/MegaLinter/.mega-linter-powershell.yml
  Testing/Linting/MegaLinter/.mega-linter-yaml.yml
  Testing/Linting/MegaLinter/.yamllint.yml
  Testing/Linting/MegaLinter/README.md
Labels: enhancement
