Repository cisagov/ScubaGear, pull requests merged in 2023-10, with the labels that each got.

#556 Remove Secure Score from MS.AAD.7.2v1
  PowerShell/ScubaGear/Modules/Connection/Connection.psm1
  PowerShell/ScubaGear/Modules/Providers/ExportAADProvider.psm1
  PowerShell/ScubaGear/RequiredVersions.ps1
  Rego/AADConfig.rego
  Testing/Unit/Rego/AAD/AADConfig_07_test.rego
  utils/UninstallModules.ps1
Labels: bug

#558 Add frequent partners to config file for Defender 2.3
  Rego/DefenderConfig.rego
  Rego/Utils/DefenderUtils.rego
  Testing/Unit/Rego/Defender/DefenderConfig_02_test.rego
  sample-config-files/defender-config.yaml
Labels: enhancement

#555 Update MS.DEFENDER.1.5v1 ATP rules check for sensitive users
  Rego/DefenderConfig.rego
  Testing/Unit/Rego/Defender/DefenderConfig_01_test.rego
  sample-config-files/defender-config.yaml
Labels: enhancement

#458 Initial Automated Functional Test Orchestrator
  .github/workflows/run_markdown_check.yaml
  PowerShell/ScubaGear/Modules/Connection/Connection.psm1
  Testing/Functional/Products/FunctionalTestUtils.ps1
  Testing/Functional/Products/Products.Tests.ps1
  Testing/Functional/Products/TestPlans/aad.testplan.yaml
  Testing/Functional/Products/TestPlans/exo.testplan.yaml
  Testing/Functional/Products/TestPlans/sharepoint.testplan.yaml
  Testing/Functional/Products/TestPlans/teams.testplan.yaml
  Testing/Functional/SmokeTest/SmokeTest002.Tests.ps1
  Testing/Functional/SmokeTest/UpdateSelenium.ps1
Labels: enhancement

#542 Sharepoint 1.3 to check domain and security group & 1.4 to check the same account for external sharing
  Rego/OneDriveConfig.rego
  Rego/SharepointConfig.rego
  Testing/Unit/Rego/Sharepoint/SharepointConfig_01_test.rego
Labels: enhancement

#572 Update powerbi.md to align with tech editor comments
  baselines/powerbi.md
Labels: baseline-document

#566 Update MS.DEFENDER.2.2v1 to assess agency domains in impersonation protection
  Rego/DefenderConfig.rego
  Testing/Unit/Rego/Defender/DefenderConfig_02_test.rego
  sample-config-files/defender-config.yaml
Labels: enhancement

#578 Fix failing OneDrive unit tests
  Testing/RunUnitTests.ps1
  Testing/Unit/PowerShell/RunRego/Run-Rego.Tests.ps1
Labels: bug

#588 MS.TEAMS.5.* hotfix
  Rego/TeamsConfig.rego
  Testing/Unit/Rego/Teams/TeamsConfig_05-test.rego
Labels: bug

#527 Update EXO code to align to revised emerald baseline
  PowerShell/ScubaGear/Modules/Providers/ExportEXOProvider.psm1
  Rego/EXOConfig.rego
  Rego/Utils/ReportUtils.rego
  Testing/Unit/Rego/EXO/EXOConfig_01_test.rego
  Testing/Unit/Rego/EXO/EXOConfig_02_test.rego
  Testing/Unit/Rego/EXO/EXOConfig_03_test.rego
  Testing/Unit/Rego/EXO/EXOConfig_04_test.rego
  Testing/Unit/Rego/EXO/EXOConfig_05_test.rego
  Testing/Unit/Rego/EXO/EXOConfig_06_test.rego
  Testing/Unit/Rego/EXO/EXOConfig_07_test.rego
  Testing/Unit/Rego/EXO/EXOConfig_08_test.rego
  Testing/Unit/Rego/EXO/EXOConfig_09_test.rego
  Testing/Unit/Rego/EXO/EXOConfig_10_test.rego
  Testing/Unit/Rego/EXO/EXOConfig_11_test.rego
  Testing/Unit/Rego/EXO/EXOConfig_12_test.rego
  Testing/Unit/Rego/EXO/EXOConfig_13_test.rego
  Testing/Unit/Rego/EXO/EXOConfig_14_test.rego
  Testing/Unit/Rego/EXO/EXOConfig_15_test.rego
  Testing/Unit/Rego/EXO/EXOConfig_16_test.rego
  Testing/Unit/Rego/EXO/EXOConfig_17_test.rego
  baselines/exo.md
Labels: enhancement

#574 Update MS.DEFENDER.4.1 and MS.DEFENDER.4.2 assessment checks
  Rego/DefenderConfig.rego
  Testing/Unit/Rego/Defender/DefenderConfig_04_test.rego
Labels: enhancement

#602 Update and fix MS.DEFENDER.4.3-4.6 for newest baseline
  Rego/DefenderConfig.rego
  Testing/Unit/Rego/Defender/DefenderConfig_04_test.rego
Labels: bug, enhancement

#606 Clarify MS.EXO.5.1v1 implementation instructions for per mailbox exception
  baselines/exo.md
Labels: bug, baseline-document

#582 Teams automated functional test plan
  Testing/Functional/Products/Products.Tests.ps1
  Testing/Functional/Products/TestPlans/teams.gcc.testplan.yaml
  Testing/Functional/Products/TestPlans/teams.testplan.yaml
  Testing/Unit/Rego/Teams/TeamsConfig_01-test.rego
Labels: Testing

#584 finalize AAD functional test plans, fix Rego bug for 7.4 and change AAD P2 references to new license name
  README.md
  Rego/AADConfig.rego
  Testing/Functional/Products/FunctionalTestUtils.ps1
  Testing/Functional/Products/Products.Tests.ps1
  Testing/Functional/Products/TestPlans/aad.g3.testplan.yaml
  Testing/Functional/Products/TestPlans/aad.g5.testplan.yaml
  Testing/Functional/Products/TestPlans/aad.testplan.yaml
  Testing/Unit/Rego/AAD/AADConfig_02_test.rego
  Testing/Unit/Rego/AAD/AADConfig_07_test.rego
  baselines/aad.md
Labels: bug, enhancement, baseline-document, Testing

#613 Correct unit test case for teams
  Testing/Unit/Rego/Teams/TeamsConfig_01-test.rego
Labels: bug

#609 power platform automated functional test plan
  Testing/Functional/Products/TestPlans/powerplatform.testplan.yaml
Labels: Testing

#569 Add SharePoint Test Plans
  Testing/Functional/Products/FunctionalTestUtils.ps1
  Testing/Functional/Products/Products.Tests.ps1
  Testing/Functional/Products/TestPlans/sharepoint.pnp.testplan.yaml
  Testing/Functional/Products/TestPlans/sharepoint.spo.testplan.yaml
  Testing/Unit/Rego/Sharepoint/SharepointConfig_01_test.rego
Labels: enhancement, Testing

#594 Add Regal for linting Rego
  .github/workflows/run_opa_tests.yaml
  .regal/config.yaml
  Rego/AADConfig.rego
  Rego/DefenderConfig.rego
  Rego/EXOConfig.rego
  Rego/PowerPlatformConfig.rego
  Rego/SharepointConfig.rego
  Rego/TeamsConfig.rego
  Rego/Utils/PolicyUtils.rego
  Rego/Utils/ReportUtils.rego
  Testing/Unit/Rego/PowerPlatform/PowerPlatformConfig_05_test.rego
  Testing/Unit/Rego/Teams/TeamsConfig_01_test.rego
  Testing/Unit/Rego/Teams/TeamsConfig_02_test.rego
  Testing/Unit/Rego/Teams/TeamsConfig_03_test.rego
  Testing/Unit/Rego/Teams/TeamsConfig_04_test.rego
  Testing/Unit/Rego/Teams/TeamsConfig_05_test.rego
  Testing/Unit/Rego/Teams/TeamsConfig_06_test.rego
  Testing/Unit/Rego/Teams/TeamsConfig_07_test.rego
  Testing/Unit/Rego/Teams/TeamsConfig_08_test.rego
Labels: enhancement, public-reported

#611 Share point1.4v1 issue
  Rego/SharepointConfig.rego
Labels: bug

#618 Fix Exchange test plan failing for DKIM compliant test
  Testing/Functional/Products/TestPlans/exo.testplan.yaml
Labels: bug, Testing
