Repository cisagov/ScubaGear, pull requests merged in 2023-03, with the labels that each got.

#166 Reverts Get-AADTenantDetail function back to its 0.2.0 state.
  PowerShell/ScubaGear/Modules/Providers/ExportAADProvider.psm1
Labels: bug

#193 Restrict OPA tests action to version <0.50
  .github/workflows/run_opa_tests.yaml
Labels: bug

#177 Add DNS retry
  PowerShell/ScubaGear/Modules/Providers/ExportEXOProvider.psm1
Labels: enhancement

#189 Onedrive with Service Principal
  Rego/OneDriveConfig.rego
  Testing/Unit/Rego/OneDrive/OneDriveConfig2_01_test.rego
  Testing/Unit/Rego/OneDrive/OneDriveConfig2_02_test.rego
  Testing/Unit/Rego/OneDrive/OneDriveConfig2_03_test.rego
Labels: bug

#111 54 cap policy exclusions
  PowerShell/ScubaGear/Modules/Orchestrator.psm1
  Rego/AADConfig.rego
  Testing/Unit/Rego/AAD/AADConfig2_01_test.rego
  Testing/Unit/Rego/AAD/AADConfig2_02_test.rego
  Testing/Unit/Rego/AAD/AADConfig2_03_test.rego
  Testing/Unit/Rego/AAD/AADConfig2_04_test.rego
  Testing/Unit/Rego/AAD/AADConfig2_09_test.rego
  Testing/Unit/Rego/AAD/AADConfig2_10_test.rego
  Testing/Unit/Rego/AAD/AADConfig2_13_test.rego
  sample-config-files/aad-config.yaml
Labels: enhancement

#207 Update the README to document service principals
  README.md
  images/appserviceprincipal-api-permssions.png
Labels: documentation

#220 Scuba release should be in root folder
  .github/workflows/run_release.yaml
Labels: bug

#217 Fix bug with DKIM and DMARC
  Rego/EXOConfig.rego
  Testing/Unit/Rego/EXO/EXOConfig2_03_test.rego
  Testing/Unit/Rego/EXO/EXOConfig2_04_test.rego
Labels: bug
