Repository cisagov/ScubaGear, pull requests merged in 2023-01, with the labels that each got.

#103 Update cmdlet for Teams 2.10
  Rego/TeamsConfig.rego
Labels: bug

#109 Updated comment help for RunFunctionalTest.ps1
  Testing/RunFunctionalTests.ps1
Labels: documentation

#107 Bug Fix: RegoCachedProviderTesting.ps1 file paths
  Testing/Functional/RegoCachedProviderTesting.ps1
Labels: bug

#112 Updated OneDrive 2.3 policy
  Rego/OneDriveConfig.rego
  Testing/Unit/Rego/OneDrive/OneDriveConfig2_03_test.rego
Labels: bug

#114 Add error handling for Power Platform
  PowerShell/ScubaGear/Modules/Orchestrator.psm1
  PowerShell/ScubaGear/Modules/Providers/ExportPowerPlatformProvider.psm1
  Rego/PowerPlatformConfig.rego
  Testing/Unit/Rego/PowerPlatform/PowerPlatformConfig2_01_test.rego
  Testing/Unit/Rego/PowerPlatform/PowerPlatformConfig2_02_test.rego
  Testing/Unit/Rego/PowerPlatform/PowerPlatformConfig2_03_test.rego
Labels: enhancement

#120 Implement code signing and basic pipeline to create draft releases.
  .github/workflows/run_release.yaml
Labels: enhancement

#131 Set encoding explictly
  PowerShell/ScubaGear/Modules/Orchestrator.psm1
Labels: bug

#121 Fix Defender 2.2 Policy 3 bug when DLP policy in test mode
  Rego/DefenderConfig.rego
  Testing/Unit/Rego/Defender/DefenderConfig2_02_test.rego
Labels: bug

#138 Hotfix the fatal error caused by duplicate JSON keys being generated in the EXO Provider
  PowerShell/ScubaGear/Modules/Providers/ExportEXOProvider.psm1
Labels: bug

#129 113 aad 24 title outdated
  Rego/AADConfig.rego
  Testing/Unit/Rego/AAD/AADConfig2_04_test.rego
Labels: bug
