Repository cisagov/ScubaGear, pull requests merged in 2023-07, with the labels that each got.

#408 Update aad scubagear code to align to revised baseline
  Rego/AADConfig.rego
  Testing/Unit/Rego/AAD/AADConfig_01_test.rego
  Testing/Unit/Rego/AAD/AADConfig_02_test.rego
  Testing/Unit/Rego/AAD/AADConfig_03_test.rego
  Testing/Unit/Rego/AAD/AADConfig_04_test.rego
  Testing/Unit/Rego/AAD/AADConfig_05_test.rego
  Testing/Unit/Rego/AAD/AADConfig_06_test.rego
  Testing/Unit/Rego/AAD/AADConfig_07_test.rego
  Testing/Unit/Rego/AAD/AADConfig_08_test.rego
  Testing/Unit/Rego/AAD/AADConfig_09_test.rego
  Testing/Unit/Rego/AAD/AADConfig_10_test.rego
  Testing/Unit/Rego/AAD/AADConfig_11_test.rego
  Testing/Unit/Rego/AAD/AADConfig_12_test.rego
  Testing/Unit/Rego/AAD/AADConfig_13_test.rego
  Testing/Unit/Rego/AAD/AADConfig_14_test.rego
  Testing/Unit/Rego/AAD/AADConfig_15_test.rego
  Testing/Unit/Rego/AAD/AADConfig_16_test.rego
  Testing/Unit/Rego/AAD/AADConfig_17_test.rego
  Testing/Unit/Rego/AAD/AADConfig_18_test.rego
  sample-config-files/aad-config.yaml
Labels: enhancement

#414 Update Secure Baseline parser (for Policy Id)
  PowerShell/ScubaGear/Modules/CreateReport/CreateReport.psm1
  Testing/Unit/PowerShell/CreateReport/CreateReportStubs/TestResults.json
  Testing/Unit/PowerShell/CreateReport/Import-SecureBaseline.Tests.ps1
  Testing/Unit/PowerShell/CreateReport/New-Report.Tests.ps1
Labels: enhancement

#333 Teams email integration patch
  Rego/TeamsConfig.rego
  Testing/Unit/Rego/Teams/TeamsConfig2_07_test.rego
Labels: bug

#424 Address Power Platform pilot comments and substantive changes in the baseline document Part 2
  baselines/powerplatform.md
Labels: baseline-document

#418 Update Smoke Test to handle CAP
  Testing/Functional/SmokeTest/SmokeTest001.Tests.ps1
  Testing/Functional/SmokeTest/SmokeTest002.Tests.ps1
Labels: bug, enhancement

#428 Update MS.AAD.7.6v1 rego to only apply to global admin
  Rego/AADConfig.rego
  Testing/Unit/Rego/AAD/AADConfig_07_test.rego
Labels: enhancement

#393 Combine Sharepoint with OneDrive and address feedback from review period
  baselines/onedrive.md
  baselines/sharepoint.md
  baselines/sharepointonedrive.md
Labels: baseline-document

#440 Update EXO PowerShell module minimum version to 3.2
  PowerShell/ScubaGear/RequiredVersions.ps1
Labels: bug

#433 Implement MS.AAD.3.1v1 phishing resistant mfa for all users
  PowerShell/ScubaGear/RequiredVersions.ps1
  Rego/AADConfig.rego
  Rego/Utils/PolicyUtils.rego
  Testing/Unit/Rego/AAD/AADConfig_03_test.rego
Labels: enhancement

#416 Add rego for MS.AAD.3.8v1 - Managed device required for MFA registration
  Rego/AADConfig.rego
  Testing/Unit/Rego/AAD/AADConfig_03_test.rego
Labels: enhancement

#446 Remove MS Graph 2.0 from GitHub Action, Run PowerShell Tests
  .github/workflows/run_powershell_tests.yaml
  .github/workflows/run_smoke_test.yaml
Labels: bug

#438 Update unit test script
  Testing/RunUnitTests.ps1
Labels: bug

#403 Adjudicate substantive changes to the powerbi baseline markdown following the new format
  baselines/powerbi.md
Labels: baseline-document

#447 Add EXO rationales
  baselines/exo.md
Labels: baseline-document

#432 Update ScubaGear code for AAD baseline policy 7.4
  Rego/AADConfig.rego
  Testing/Unit/Rego/AAD/AADConfig_07_test.rego
  sample-config-files/aad-config.yaml
Labels: enhancement

#436 Address EXO comment and structural changes in the baseline document
  baselines/exo.md
Labels: baseline-document

#397 Teams baseline update based on the pilot feedback and internal testing
  baselines/teams.md
Labels: baseline-document
