Repository cisagov/ScubaGear, pull requests merged in 2024-09, with the labels that each got.

#1297 Remove workflow unit tests from CI pipeline
  .github/workflows/run_pipeline.yaml
Labels: enhancement, Testing

#1292 Reworked EXO Unit Tests to use 1 JSON
  PowerShell/ScubaGear/Testing/Unit/Rego/EXO/EXOBaseConfig.rego
  PowerShell/ScubaGear/Testing/Unit/Rego/EXO/EXOConfig_01_test.rego
  PowerShell/ScubaGear/Testing/Unit/Rego/EXO/EXOConfig_02_test.rego
  PowerShell/ScubaGear/Testing/Unit/Rego/EXO/EXOConfig_03_test.rego
  PowerShell/ScubaGear/Testing/Unit/Rego/EXO/EXOConfig_04_test.rego
  PowerShell/ScubaGear/Testing/Unit/Rego/EXO/EXOConfig_05_test.rego
  PowerShell/ScubaGear/Testing/Unit/Rego/EXO/EXOConfig_06_test.rego
  PowerShell/ScubaGear/Testing/Unit/Rego/EXO/EXOConfig_07_test.rego
  PowerShell/ScubaGear/Testing/Unit/Rego/EXO/EXOConfig_12_test.rego
  PowerShell/ScubaGear/Testing/Unit/Rego/EXO/EXOConfig_13_test.rego
Labels: enhancement, Testing

#1092 Add a backup path to look for the OPA executable in the current directory
  PowerShell/ScubaGear/Modules/RunRego/RunRego.psm1
  PowerShell/ScubaGear/Modules/ScubaConfig/ScubaConfig.psm1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/RunRego/Run-Rego.Tests.ps1
  docs/prerequisites/dependencies.md
Labels: enhancement

#1300 Add initialize-scuba to execution page
  docs/execution/execution.md
Labels: documentation

#1281 Enhance csv version of output
  PowerShell/ScubaGear/Modules/Orchestrator.psm1
  PowerShell/ScubaGear/Modules/ScubaConfig/ScubaConfig.psm1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Orchestrator/ConvertTo-ResultsCsv.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Orchestrator/Format-PlainText.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Support/Copy-ScubaSampleReport.Tests.ps1
  Testing/Functional/SmokeTest/SmokeTest001.Tests.ps1
  docs/configuration/parameters.md
  docs/execution/reports.md
Labels: enhancement

#1293 Update Iceburg SCBs to adjudicate comments made by JCDC during CB publication review
  PowerShell/ScubaGear/baselines/aad.md
  PowerShell/ScubaGear/baselines/defender.md
  PowerShell/ScubaGear/baselines/exo.md
  PowerShell/ScubaGear/baselines/powerbi.md
  PowerShell/ScubaGear/baselines/powerplatform.md
  PowerShell/ScubaGear/baselines/sharepoint.md
  PowerShell/ScubaGear/baselines/teams.md
Labels: baseline-document

#1302 Fix encoding issue by removing BOM from provider output files
  PowerShell/ScubaGear/Modules/CreateReport/CreateReport.psm1
  PowerShell/ScubaGear/Modules/Orchestrator.psm1
  PowerShell/ScubaGear/Modules/Utility/Utility.psm1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/CreateReport/New-Report.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Orchestrator/Invoke-ProviderList.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Support/New-SCuBAConfig.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Utility/Get-Utf8NoBom.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Utility/Set-Utf8NoBom.Tests.ps1
  Testing/Functional/Products/FunctionalTestUtils.ps1
  Testing/Functional/Products/Products.Tests.ps1
Labels: bug, public-reported

#1316 Make ScubaResults.json the default JSON output
  PowerShell/ScubaGear/Modules/Orchestrator.psm1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Orchestrator/Invoke-Scuba.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Orchestrator/Invoke-ScubaCached.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Orchestrator/Invoke-ScubaConfig.Tests.ps1
  Testing/Functional/Products/Products.Tests.ps1
  Testing/Functional/SmokeTest/SmokeTest001.Tests.ps1
  docs/configuration/parameters.md
  docs/execution/reports.md
Labels: breaking change, enhancement

#1310 Enhance AAD provider to handle nested PIM groups and refactor Get-PrivilegedUser to reduce code duplication
  PowerShell/ScubaGear/Modules/Providers/ExportAADProvider.psm1
  PowerShell/ScubaGear/RequiredVersions.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/AADProvider/LoadObjectDataIntoPrivilegedUserHashtable.Tests.ps1
  utils/UninstallModules.ps1
Labels: bug, enhancement

#1334 Fix functional testing and cached output errors
  PowerShell/ScubaGear/Modules/Orchestrator.psm1
  Testing/Functional/Products/FunctionalTestUtils.ps1
  Testing/Functional/Products/TestPlans/sharepoint.pnp.testplan.yaml
Labels: bug, Testing
