Repository cisagov/ScubaGear, pull requests merged in 2024-12, with the labels that each got.

#1435 Convert baseline markdown files to text and HTML
  .github/workflows/convert_baselines.yaml
Labels: enhancement

#1388 Allow Users to Specify Installing to AllUsers via new $Scope Variable in Initialize-SCuBA
  PowerShell/ScubaGear/Modules/Support/Support.psm1
Labels: enhancement

#1387 Correct Erroring Default Variable Assignments on Systems with unique file paths
  PowerShell/ScubaGear/Modules/ScubaConfig/ScubaConfig.psm1
Labels: bug

#1447 Remove all instances of policy MS.SHAREPOINT4.2v1 due to Microsoft update to custom scripting settings
  PowerShell/ScubaGear/Rego/SharepointConfig.rego
  PowerShell/ScubaGear/Testing/Unit/PowerShell/CreateReport/CreateReportStubs/TestResults.json
  PowerShell/ScubaGear/Testing/Unit/Rego/Sharepoint/SharepointConfig_04_test.rego
  PowerShell/ScubaGear/baselines/removedpolicies.md
  PowerShell/ScubaGear/baselines/sharepoint.md
  Testing/Functional/Products/TestPlans/sharepoint.pnp.testplan.yaml
  Testing/Functional/Products/TestPlans/sharepoint.spo.testplan.yaml
Labels: bug, baseline-document

#1440 Update SCB acronym to read as "Secure Configuration Baseline" throughout repo
  PowerShell/ScubaGear/Testing/Unit/PowerShell/CreateReport/CreateReportStubs/aad.md
  PowerShell/ScubaGear/baselines/aad.md
  PowerShell/ScubaGear/baselines/defender.md
  PowerShell/ScubaGear/baselines/exo.md
  PowerShell/ScubaGear/baselines/powerbi.md
  PowerShell/ScubaGear/baselines/powerplatform.md
  PowerShell/ScubaGear/baselines/removedpolicies.md
  PowerShell/ScubaGear/baselines/sharepoint.md
  PowerShell/ScubaGear/baselines/teams.md
  README.md
Labels: documentation, baseline-document

#1450 Write unit tests for Invoke PSSA
  Testing/workflow/Invoke-PSSA.Tests.ps1
  utils/workflow/Initialize-ScubaGearForTesting.ps1
  utils/workflow/Install-SeleniumForTesting.ps1
  utils/workflow/Invoke-PSSA.ps1
Labels: enhancement

#1460 Change tests for MS.AAD.5.4v1 for teams group consent to not-implemented as setting is deprecated
  PowerShell/ScubaGear/Rego/AADConfig.rego
  PowerShell/ScubaGear/Testing/Unit/Rego/AAD/AADBaseConfig.rego
  PowerShell/ScubaGear/Testing/Unit/Rego/AAD/AADConfig_05_test.rego
  Testing/Functional/Products/TestPlans/aad.testplan.yaml
Labels: microsoft roadmap

#1468 Added StackTrace multiple locations in source code to assist when troubleshooting
  PowerShell/ScubaGear/Modules/Connection/Connection.psm1
  PowerShell/ScubaGear/Modules/Orchestrator.psm1
  PowerShell/ScubaGear/Modules/Providers/ExportAADProvider.psm1
  PowerShell/ScubaGear/Modules/Providers/ExportDefenderProvider.psm1
  PowerShell/ScubaGear/Modules/Providers/ExportEXOProvider.psm1
  PowerShell/ScubaGear/Modules/Providers/ExportPowerPlatformProvider.psm1
  PowerShell/ScubaGear/Modules/Providers/ExportTeamsProvider.psm1
  PowerShell/ScubaGear/Modules/Providers/ProviderHelpers/CommandTracker.psm1
  PowerShell/ScubaGear/Modules/RunRego/RunRego.psm1
Labels: enhancement

#1384 Remove html elements from ScubaResults.json
  PowerShell/ScubaGear/Modules/Orchestrator.psm1
Labels: enhancement

#1424 Added version update notification
  PowerShell/ScubaGear/CheckVersion.ps1
  PowerShell/ScubaGear/Modules/ScubaConfig/ScubaConfig.psm1
  PowerShell/ScubaGear/ScubaGear.psd1
  docs/configuration/configuration.md
  docs/configuration/parameters.md
Labels: enhancement

#1475 Update sample reports for 1.5.0 release
  PowerShell/ScubaGear/Sample-Reports/ActionPlan.csv
  PowerShell/ScubaGear/Sample-Reports/BaselineReports.html
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/AADReport.html
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/AADReport.json
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/DefenderReport.html
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/DefenderReport.json
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/EXOReport.html
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/EXOReport.json
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/PowerPlatformReport.html
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/PowerPlatformReport.json
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/SharePointReport.html
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/SharePointReport.json
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/TeamsReport.html
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/TeamsReport.json
  PowerShell/ScubaGear/Sample-Reports/ProviderSettingsExport.json
  PowerShell/ScubaGear/Sample-Reports/ScubaResults.csv
  PowerShell/ScubaGear/Sample-Reports/ScubaResults_550fbc57-f602-4b40.json
  PowerShell/ScubaGear/Sample-Reports/TestResults.csv
  PowerShell/ScubaGear/Sample-Reports/TestResults.json
Labels: documentation
