Repository cisagov/ScubaGear, pull requests merged in 2024-05, with the labels that each got.

#1081 fixed functional test for AAD 5.3 so that it only produces a single EnableAdminConsentRequests field
  Testing/Functional/Products/TestPlans/aad.testplan.yaml
Labels: bug

#1082 fixed AAD functional test failures for non-compliant tests 7.4 7.5 when running in GitHub actions
  Testing/Functional/Products/TestPlans/aad.g5.testplan.yaml
Labels: bug

#1083 Fixed documentation comments in sharepoint.md
  PowerShell/ScubaGear/baselines/sharepoint.md
Labels: bug, baseline-document, public-reported

#1076 Modify Sharepoint policies to only execute when applicable
  PowerShell/ScubaGear/Rego/SharepointConfig.rego
  PowerShell/ScubaGear/Rego/Utils/ReportDetails.rego
  PowerShell/ScubaGear/Testing/Unit/Rego/Sharepoint/SharepointConfig_01_test.rego
  PowerShell/ScubaGear/Testing/Unit/Rego/Sharepoint/SharepointConfig_03_test.rego
  Testing/Functional/Products/TestPlans/sharepoint.pnp.testplan.yaml
  Testing/Functional/Products/TestPlans/sharepoint.spo.testplan.yaml
Labels: bug

#1090 1016 create template markdown for discontinued policy ids for m365 & gws
  PowerShell/ScubaGear/baselines/removedpolicies.md
  baselines/README.md
Labels: baseline-document

#1100 Bump ScubaGear PowerShell module dependency versions
  PowerShell/ScubaGear/RequiredVersions.ps1
Labels: enhancement, upstream update

#1120 Updating the CAP exclusion for AAD
  PowerShell/ScubaGear/Modules/CreateReport/CreateReport.psm1
Labels: enhancement

#1119 Add reference URL to ScubaResults.json
  PowerShell/ScubaGear/Modules/CreateReport/CreateReport.psm1
Labels: enhancement

#1116 Pin ExchangeOnlineManagement module version to < v3.5
  PowerShell/ScubaGear/RequiredVersions.ps1
Labels: bug

#1091 Mapping product names
  PowerShell/ScubaGear/Modules/CreateReport/CreateReport.psm1
  PowerShell/ScubaGear/Modules/CreateReport/MicrosoftLicenseToProductNameMappings.csv
  Testing/Functional/SmokeTest/SmokeTest002.Tests.ps1
Labels: enhancement

#1105 Add accessibility improvements to the reports
  PowerShell/ScubaGear/Modules/CreateReport/CreateReport.psm1
  PowerShell/ScubaGear/Modules/CreateReport/IndividualReport/IndividualReport.html
  PowerShell/ScubaGear/Modules/CreateReport/ParentReport/ParentReport.html
  PowerShell/ScubaGear/Modules/CreateReport/scripts/ParentReport.js
  PowerShell/ScubaGear/Modules/CreateReport/scripts/main.js
  PowerShell/ScubaGear/Modules/CreateReport/styles/ParentReportStyle.css
  PowerShell/ScubaGear/Modules/CreateReport/styles/main.css
Labels: enhancement

#929 Enhanced Defender license warnings for policy groups 2 and 4
  PowerShell/ScubaGear/Modules/Providers/ExportDefenderProvider.psm1
  PowerShell/ScubaGear/Rego/DefenderConfig.rego
  PowerShell/ScubaGear/Rego/Utils/Defender.rego
  PowerShell/ScubaGear/Testing/Unit/Rego/Defender/DefenderConfig_01_test.rego
  PowerShell/ScubaGear/Testing/Unit/Rego/Defender/DefenderConfig_02_test.rego
  PowerShell/ScubaGear/Testing/Unit/Rego/Defender/DefenderConfig_04_test.rego
  Testing/Functional/Products/TestPlans/defender.g3.testplan.yaml
Labels: bug

#782 Dedupe $ProductNames
  PowerShell/ScubaGear/Modules/Orchestrator.psm1
  PowerShell/ScubaGear/Modules/ScubaConfig/ScubaConfig.psm1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Orchestrator/Invoke-Scuba.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/ScubaConfig/ScubaConfigJsonDuplicateProviderTests.ps1
Labels: bug
