Repository cisagov/ScubaGear, pull requests merged in 2024-02, with the labels that each got.

#886 Fix ProductNames wildcard processing
  PowerShell/ScubaGear/Modules/Orchestrator.psm1
  PowerShell/ScubaGear/Modules/ScubaConfig/ScubaConfig.psm1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Orchestrator/Invoke-ScubaConfig.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Orchestrator/product_wildcard_config_test.yaml
  PowerShell/ScubaGear/Testing/Unit/PowerShell/ScubaConfig/ScubaConfigDelete.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/ScubaConfig/config_test.json
  PowerShell/ScubaGear/Testing/Unit/PowerShell/ScubaConfig/config_test.yaml
  sample-config-files/typical_config.yaml
Labels: bug

#893 Fixes ScubaConfig.LoadConfig repeated invocations
  PowerShell/ScubaGear/Modules/ScubaConfig/ScubaConfig.psm1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/ScubaConfig/ScubaConfigLoadConfig.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/ScubaConfig/config_test_load_config1.json
  PowerShell/ScubaGear/Testing/Unit/PowerShell/ScubaConfig/config_test_load_config2.json
Labels: bug

#896 Remove an unnecessary cmdlet from aad policy check 5.3 to improve performance of the provider
  PowerShell/ScubaGear/Modules/Providers/ExportAADProvider.psm1
  PowerShell/ScubaGear/Rego/AADConfig.rego
  PowerShell/ScubaGear/Testing/Unit/PowerShell/CreateReport/CreateReportStubs/ProviderSettingsExport.json
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/AADProvider/Export-AADProvider.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/Rego/AAD/AADConfig_05_test.rego
  PowerShell/ScubaGear/baselines/aad.md
  Testing/Functional/Products/TestPlans/aad.testplan.yaml
Labels: enhancement

#894 OPA executable path default value inconsistent between invoke scuba with or without configfilepath
  PowerShell/ScubaGear/Modules/Orchestrator.psm1
  PowerShell/ScubaGear/Modules/ScubaConfig/ScubaConfig.psm1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Orchestrator/Invoke-Scuba.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Orchestrator/Invoke-ScubaConfig.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/ScubaConfig/ScubaConfigJson.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/ScubaConfig/ScubaConfigJsonMissingDefaults.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/ScubaConfig/ScubaConfigLoadConfig.Tests.ps1
Labels: bug

#862 Allow user to copy sample (read-only) files packaged with module
  PowerShell/ScubaGear/Modules/Support/Support.psm1
  PowerShell/ScubaGear/Sample-Config-Files/aad-config.yaml
  PowerShell/ScubaGear/Sample-Config-Files/basic_config.yaml
  PowerShell/ScubaGear/Sample-Config-Files/creds_config.yaml
  PowerShell/ScubaGear/Sample-Config-Files/defender-config.yaml
  PowerShell/ScubaGear/Sample-Config-Files/full_config.yaml
  PowerShell/ScubaGear/Sample-Config-Files/sample-config.json
  PowerShell/ScubaGear/Sample-Config-Files/sample-config.yaml
  PowerShell/ScubaGear/Sample-Config-Files/typical_config.yaml
  PowerShell/ScubaGear/Sample-Reports/BaselineReports.html
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/AADReport.html
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/DefenderReport.html
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/EXOReport.html
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/PowerPlatformReport.html
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/SharePointReport.html
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/TeamsReport.html
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/images/angle-down-solid.svg
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/images/angle-right-solid.svg
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/images/cisa_logo.png
  PowerShell/ScubaGear/Sample-Reports/ProviderSettingsExport.json
  PowerShell/ScubaGear/Sample-Reports/TestResults.csv
  PowerShell/ScubaGear/Sample-Reports/TestResults.json
  PowerShell/ScubaGear/ScubaGear.psd1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Support/Copy-ScubaSampleConfigFile.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Support/Copy-ScubaSampleReport.Tests.ps1
  Testing/Functional/SmokeTest/SmokeTest001.Tests.ps1
  sample-config-files/README.md
  sample-report/README.md
Labels: enhancement

#908 Add MSGraph and SPO library max versions
  PowerShell/ScubaGear/RequiredVersions.ps1
Labels: bug

#907 add TLP:CLEAR information note to powerbi baseline
  PowerShell/ScubaGear/baselines/powerbi.md
Labels: bug, baseline-document

#895 update supported opa versions to 0.61
  OPA.ps1
  README.md
  SetUp.ps1
Labels: enhancement

#852 Add Least Privilege Score Check to Policy MS.AAD.7.2v1
  PowerShell/ScubaGear/Rego/AADConfig.rego
  PowerShell/ScubaGear/Testing/Unit/Rego/AAD/AADConfig_07_test.rego
  Testing/Functional/Products/TestPlans/aad.testplan.yaml
Labels: enhancement

#912 Create initial software dev pipeline
  .github/workflows/run_linter_powershell.yaml
  .github/workflows/run_linter_yaml.yaml
  .github/workflows/run_markdown_check.yaml
  .github/workflows/run_opa_tests.yaml
  .github/workflows/run_pipeline.yaml
  .github/workflows/run_powershell_tests.yaml
Labels: enhancement

#922 Version bump main to v1.1.1
  PowerShell/ScubaGear/ScubaGear.psd1
  README.md
Labels: version bump

#924 Fixes Broken Links in Baseline Report
  PowerShell/ScubaGear/Modules/CreateReport/CreateReport.psm1
Labels: bug

#916 Force enhanced error handling to all updated providers
  PowerShell/ScubaGear/Modules/CreateReport/CreateReport.psm1
Labels: bug

#873 Support prerelease publishing of modules to package repository
  .github/workflows/run_publish_package.yaml
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Utils/DeployUtils.Tests.ps1
  utils/DeployUtils.ps1
Labels: enhancement

#927 Update version in release filename to 1-1-1
  README.md
Labels: bug, documentation, version bump

#870 Refactor support scripts to functions
  .github/workflows/run_functional_product_tests.yaml
  .github/workflows/run_powershell_tests.yaml
  .github/workflows/run_publish_package.yaml
  .github/workflows/run_release.yaml
  .github/workflows/run_smoke_test.yaml
  OPA.ps1
  PowerShell/ScubaGear/Dependencies.ps1
  PowerShell/ScubaGear/Modules/Support/Support.psm1
  PowerShell/ScubaGear/ScubaGear.psd1
  README.md
  SetUp.ps1
  Testing/Functional/Products/Products.Tests.ps1
  Testing/Functional/RegoCachedProviderTesting.ps1
  Testing/Functional/SmokeTest/SmokeTestUtils.ps1
  utils/RegoCachedProviderTesting.ps1
  utils/RunSCuBA.ps1
  utils/ScubaGearSupport.ps1
Labels: documentation, enhancement

#902 Implement MS.AAD.3.5.v1 authentication methods SMS, voice call and email OTP shall be disabled
  PowerShell/ScubaGear/Modules/Providers/ExportAADProvider.psm1
  PowerShell/ScubaGear/Modules/ScubaConfig/ScubaConfig.psm1
  PowerShell/ScubaGear/Rego/AADConfig.rego
  PowerShell/ScubaGear/Rego/Utils/KeyFunctions.rego
  PowerShell/ScubaGear/Rego/Utils/ReportDetails.rego
  PowerShell/ScubaGear/Testing/Unit/Rego/AAD/AADConfig_03_test.rego
  Testing/Functional/Products/FunctionalTestUtils.ps1
  Testing/Functional/Products/Products.Tests.ps1
  Testing/Functional/Products/TestPlans/aad.testplan.yaml
Labels: enhancement

#918 Add app level defaults
  PowerShell/ScubaGear/Modules/Orchestrator.psm1
  PowerShell/ScubaGear/Modules/ScubaConfig/ScubaConfig.psm1
Labels: enhancement

#933 Add and Apply a README Style Guide to the current README
  CONTENTSTYLEGUIDE.md
  README.md
Labels: documentation

#914 Add PowerShell unit test cases for when service principals are passed into scubagear
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Connection/Connect-Tenant.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Orchestrator/Get-ServicePrincipalParams.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Orchestrator/Invoke-Connection.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Orchestrator/Invoke-Scuba.Tests.ps1
Labels: enhancement, Testing

#936 Add RELEASES.md and CONTRIBUTING.md to project
  CONTRIBUTING.md
  RELEASES.md
Labels: documentation, enhancement
