Repository cisagov/ScubaGear, pull requests merged in 2024-08, with the labels that each got.

#1159 Update Regal to v0.23.1
  .github/workflows/unit_test_opa.yaml
  .regal/config.yaml
  PowerShell/ScubaGear/Rego/AADConfig.rego
  PowerShell/ScubaGear/Testing/Unit/Rego/Defender/DefenderConfig_04_test.rego
Labels: upstream update, public-reported

#1241 Add assessment check for MS.DEFENDER.6.2v1
  PowerShell/ScubaGear/Modules/Connection/ConnectHelpers.psm1
  PowerShell/ScubaGear/Modules/Connection/Connection.psm1
  PowerShell/ScubaGear/Modules/Providers/ExportDefenderProvider.psm1
  PowerShell/ScubaGear/Rego/DefenderConfig.rego
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Connection/Connect-GraphHelper.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Connection/Connect-Tenant.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/DefenderProvider/Export-DefenderProvider.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/Rego/Defender/DefenderConfig_06_test.rego
  Testing/Functional/Products/TestPlans/defender.testplan.yaml
Labels: enhancement

#1234 Refactor DeployUtils and Add Unit Tests
  .github/workflows/publish_private_package.yaml
  .github/workflows/publish_public_package.yaml
  .github/workflows/run_pipeline.yaml
  Testing/workflow/DeployUtils.Tests.ps1
  Testing/workflow/Publish-ScubaGear.Tests.ps1
  utils/DeployUtils.ps1
  utils/workflow/Publish-ScubaGear.ps1
Labels: enhancement

#1137 Cleaning up and streamlining config files
  PowerShell/ScubaGear/Sample-Config-Files/aad-config.yaml
  PowerShell/ScubaGear/Sample-Config-Files/basic_config.yaml
  PowerShell/ScubaGear/Sample-Config-Files/creds_config.yaml
  PowerShell/ScubaGear/Sample-Config-Files/full_config.yaml
  PowerShell/ScubaGear/Sample-Config-Files/sample-config.yaml
  PowerShell/ScubaGear/Sample-Config-Files/typical_config.yaml
Labels: documentation

#1256 Fix build and sign GitHub release
  .github/workflows/build_sign_release.yaml
Labels: bug, infrastructure

#1261 Remove erroring support module code from Initialize-SCuBA
  PowerShell/ScubaGear/Modules/Support/Support.psm1
  Testing/workflow/Initialize-ScubaGearForTesting.Tests.ps1
Labels: bug

#1266 Fix AAD 401 authentication errors against GCC high tenants
  PowerShell/ScubaGear/Modules/Orchestrator.psm1
  PowerShell/ScubaGear/Modules/Providers/ExportAADProvider.psm1
  PowerShell/ScubaGear/Modules/Support/Support.psm1
  Testing/Functional/Products/Products.Tests.ps1
Labels: bug

#1270 Changed Sharepoint policy 1.4 to not-implemented since it relies on deprecated field RequireAcceptingAccountMatchInvitedAccount
  PowerShell/ScubaGear/Rego/SharepointConfig.rego
  PowerShell/ScubaGear/Rego/Utils/ReportDetails.rego
  PowerShell/ScubaGear/Testing/Unit/Rego/Sharepoint/SharepointBaseConfig.rego
  PowerShell/ScubaGear/Testing/Unit/Rego/Sharepoint/SharepointConfig_01_test.rego
  Testing/Functional/Products/TestPlans/sharepoint.pnp.testplan.yaml
  Testing/Functional/Products/TestPlans/sharepoint.spo.testplan.yaml
Labels: bug

#1274 Fix erroneous AD -> Entra ID rename
  PowerShell/ScubaGear/baselines/aad.md
Labels: bug, baseline-document

#1280 Fix the Azure GitHub link in the Microsoft Teams baseline markdown document
  PowerShell/ScubaGear/baselines/teams.md
Labels: bug, baseline-document

#1277 Fix failing defender functional tests
  Testing/Functional/Products/TestPlans/defender.g3.testplan.yaml
  Testing/Functional/Products/TestPlans/defender.g5.testplan.yaml
  Testing/Functional/Products/TestPlans/defender.testplan.yaml
Labels: bug, Testing

#1245 Fix some issues with the markdown in the AAD/EntraID documentation.
  PowerShell/ScubaGear/baselines/aad.md
Labels: baseline-document, public-reported
