Repository cisagov/ScubaGear, pull requests merged in 2024-04, with the labels that each got.

#1043 Fix bug with msaad52v1 only admins consent to apps
  PowerShell/ScubaGear/Rego/AADConfig.rego
  PowerShell/ScubaGear/Testing/Unit/Rego/AAD/AADConfig_05_test.rego
  Testing/Functional/Products/TestPlans/aad.testplan.yaml
  Testing/RunUnitTests.ps1
Labels: bug

#1042 Fix publish package errors
  .github/workflows/publish_package.yaml
  .github/workflows/publish_private_package.yaml
  .github/workflows/publish_public_package.yaml
  .github/workflows/run_pipeline.yaml
  .github/workflows/run_publish_package.yaml
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Utils/DeployUtils.Tests.ps1
  utils/DeployUtils.ps1
Labels: bug

#1004 Add a Workflow to check for OPA version updates
  .github/workflows/run_update_opa.yaml
  PowerShell/ScubaGear/Modules/Support/Support.psm1
  README.md
Labels: enhancement

#1057 Defender functional test plan fixes
  Testing/Functional/Products/TestPlans/defender.g3.testplan.yaml
  Testing/Functional/Products/TestPlans/defender.g5.testplan.yaml
  Testing/Functional/Products/TestPlans/defender.testplan.yaml
Labels: bug, Testing

#1068 Fix Markdown in readme
  README.md
  baselines/README.md
Labels: documentation

#1041 Add Policy Group Names to ScubaResults.json
  PowerShell/ScubaGear/Modules/CreateReport/CreateReport.psm1
  PowerShell/ScubaGear/Modules/Orchestrator.psm1
Labels: enhancement

#1066 Add GitLeaks to CI/CD Pipeline
  .github/workflows/run_pipeline.yaml
  .github/workflows/run_secret_scan.yaml
  .github/workflows/unit_test_powershell.yaml
Labels: enhancement

#1014 Enhance AAD Provider and Rego Code to automate checks for policy MS.AAD.3.3v1
  PowerShell/ScubaGear/Modules/Providers/ExportAADProvider.psm1
  PowerShell/ScubaGear/Rego/AADConfig.rego
  PowerShell/ScubaGear/Testing/Unit/Rego/AAD/AADConfig_03_test.rego
  Testing/Functional/Products/Products.Tests.ps1
  Testing/Functional/Products/TestPlans/aad.testplan.yaml
  Testing/RunUnitTests.ps1
Labels: enhancement
