Repository cisagov/ScubaGear, pull requests merged in 2024-06, with the labels that each got.

#1114 Streamline the README and add install from PSGallery instructions
  README.md
  docs/configuration/configuration.md
  docs/configuration/parameters.md
  docs/execution/execution.md
  docs/execution/reports.md
  docs/images/cisa.png
  docs/images/opa_version.png
  docs/images/scuba-process.png
  docs/installation/github.md
  docs/installation/psgallery.md
  docs/installation/uninstall.md
  docs/misc/assumptions.md
  docs/prerequisites/dependencies.md
  docs/prerequisites/interactive.md
  docs/prerequisites/noninteractive.md
  docs/prerequisites/permissions.md
  docs/troubleshooting/defender.md
  docs/troubleshooting/exchange.md
  docs/troubleshooting/graph.md
  docs/troubleshooting/power.md
  docs/troubleshooting/proxy.md
  docs/troubleshooting/tenants.md
  images/aad-mfa.png
  images/adminconsentapproval1.PNG
  images/adminconsentapproval2.PNG
  images/adminconsentapproval3.PNG
  images/adminconsentapproval4.PNG
  images/adminconsentworkflownotconfigured.PNG
  images/cloudadminuserrunningscript.PNG
  images/globaladminuserrunningscript.PNG
  images/regularuserneedadminapproval.PNG
  images/regularuserrequestapproval.PNG
  images/regularuserrequestapproval2.PNG
  images/scuba-architecture.png
  sample-config-files/README.md
Labels: documentation, enhancement

#983 Readme for the Testing - detailed instructions for functional testing usage and addition of new tests
  Testing/Readme.md
  images/FunctionalTestingFolder.png
  images/PP-1-1.png
  images/Teams-1-3.png
  images/chrome-process-kill.png
  images/chrome-process-kill2.png
  images/chrome-version.png
  images/service-principal.png
Labels: documentation, Testing

#1149 Update sample reports to v1.3.0 output examples
  PowerShell/ScubaGear/Sample-Reports/BaselineReports.html
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/AADReport.html
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/AADReport.json
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/DefenderReport.html
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/DefenderReport.json
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/EXOReport.html
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/EXOReport.json
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/PowerPlatformReport.html
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/PowerPlatformReport.json
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/SharePointReport.html
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/SharePointReport.json
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/TeamsReport.html
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/TeamsReport.json
  PowerShell/ScubaGear/Sample-Reports/ProviderSettingsExport.json
  PowerShell/ScubaGear/Sample-Reports/TestResults.csv
  PowerShell/ScubaGear/Sample-Reports/TestResults.json
Labels: documentation

#1152 Bump azure/login action to v2
  .github/workflows/build_sign_release.yaml
  .github/workflows/publish_private_package.yaml
  .github/workflows/publish_public_package.yaml
Labels: bug, upstream update

#1158 Fix pre-release candidate publishing
  .github/workflows/publish_public_package.yaml
Labels: bug

#1157 Make small improvements to the documentation
  README.md
  docs/configuration/configuration.md
  docs/configuration/parameters.md
  docs/execution/execution.md
  docs/execution/reports.md
  docs/installation/uninstall.md
  docs/prerequisites/dependencies.md
  docs/troubleshooting/graph.md
Labels: documentation, enhancement

#1095 Decouple the remaining EXO Shall/Should policies
  PowerShell/ScubaGear/Rego/EXOConfig.rego
  PowerShell/ScubaGear/Rego/Utils/ReportDetails.rego
  PowerShell/ScubaGear/Testing/Unit/PowerShell/CreateReport/CreateReportStubs/TestResults.json
  PowerShell/ScubaGear/Testing/Unit/Rego/EXO/EXOConfig_08_test.rego
  PowerShell/ScubaGear/Testing/Unit/Rego/EXO/EXOConfig_09_test.rego
  PowerShell/ScubaGear/Testing/Unit/Rego/EXO/EXOConfig_14_test.rego
  PowerShell/ScubaGear/baselines/exo.md
  Testing/Functional/Products/TestPlans/exo.testplan.yaml
Labels: baseline-document

#1153 Add DNS unit tests
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/EXOProvider/Get-ScubaDkimRecord.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/EXOProvider/Get-ScubaDkimRecords.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/EXOProvider/Get-ScubaDmarcRecord.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/EXOProvider/Get-ScubaDmarcRecords.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/EXOProvider/Get-ScubaSpfRecord.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/EXOProvider/Get-ScubaSpfRecords.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/EXOProvider/Invoke-RobustDnsTxt.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/EXOProvider/Select-DohServer.Tests.ps1
Labels: Testing

#1167 Add additional shields.io badges to README
  README.md
Labels: enhancement

#1117 Updated Azure AD policy (MS.AAD.5.2v1) instructions to match updated UI buttonology
  PowerShell/ScubaGear/baselines/aad.md
Labels: baseline-document

#1151 Refactor AAD Unit test to pull from central Jsons
  .regal/config.yaml
  PowerShell/ScubaGear/Rego/AADConfig.rego
  PowerShell/ScubaGear/Rego/Utils/KeyFunctions.rego
  PowerShell/ScubaGear/Rego/Utils/TestAssertions.rego
  PowerShell/ScubaGear/Testing/Unit/Rego/AAD/AADBaseConfig.rego
  PowerShell/ScubaGear/Testing/Unit/Rego/AAD/AADConfig_01_test.rego
  PowerShell/ScubaGear/Testing/Unit/Rego/AAD/AADConfig_02_test.rego
  PowerShell/ScubaGear/Testing/Unit/Rego/AAD/AADConfig_03_test.rego
  PowerShell/ScubaGear/Testing/Unit/Rego/AAD/AADConfig_05_test.rego
  PowerShell/ScubaGear/Testing/Unit/Rego/AAD/AADConfig_06_test.rego
  PowerShell/ScubaGear/Testing/Unit/Rego/AAD/AADConfig_07_test.rego
  PowerShell/ScubaGear/Testing/Unit/Rego/AAD/AADConfig_08_test.rego
  Testing/RunUnitTests.ps1
Labels: enhancement, Testing

#1177 Removed Extra Line of Code in EXO
  PowerShell/ScubaGear/Modules/Providers/ExportEXOProvider.psm1
Labels: bug
