Repository cisagov/ScubaGear, pull requests merged in 2024-10, with the labels that each got.

#1342 Add UUID to JSON output
  PowerShell/ScubaGear/Modules/CreateReport/ParentReport/ParentReport.html
  PowerShell/ScubaGear/Modules/CreateReport/styles/ParentReportStyle.css
  PowerShell/ScubaGear/Modules/CreateReport/styles/main.css
  PowerShell/ScubaGear/Modules/Orchestrator.psm1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Orchestrator/Invoke-ReportCreation.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Orchestrator/Invoke-ScubaCached.Tests.ps1
Labels: enhancement

#1309 Add policy check for SharePoint 3.2 when using service principal and update SharePoint 4.2 rego for deprecation
  PowerShell/ScubaGear/Modules/Providers/ExportSharePointProvider.psm1
  PowerShell/ScubaGear/Rego/SharepointConfig.rego
  PowerShell/ScubaGear/Testing/Unit/Rego/Sharepoint/SharepointBaseConfig.rego
  PowerShell/ScubaGear/Testing/Unit/Rego/Sharepoint/SharepointConfig_01_test.rego
  PowerShell/ScubaGear/Testing/Unit/Rego/Sharepoint/SharepointConfig_03_test.rego
  PowerShell/ScubaGear/Testing/Unit/Rego/Sharepoint/SharepointConfig_04_test.rego
  Testing/Functional/Products/TestPlans/sharepoint.pnp.testplan.yaml
  Testing/Functional/Products/TestPlans/sharepoint.spo.testplan.yaml
Labels: bug, enhancement

#1351 Add action plan CSV
  PowerShell/ScubaGear/Modules/Orchestrator.psm1
  PowerShell/ScubaGear/Modules/ScubaConfig/ScubaConfig.psm1
  PowerShell/ScubaGear/Sample-Config-Files/full_config.yaml
  PowerShell/ScubaGear/Sample-Config-Files/sample-config.json
  PowerShell/ScubaGear/Sample-Config-Files/sample-config.yaml
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Orchestrator/ConvertTo-ResultsCsv.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Orchestrator/Invoke-Scuba.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Orchestrator/Invoke-ScubaCached.Tests.ps1
  docs/configuration/parameters.md
  docs/execution/reports.md
Labels: enhancement

#1362 Update HTML report template title (Security Baseline Conformation -> Secure Configuration Baseline)
  PowerShell/ScubaGear/Modules/CreateReport/ParentReport/ParentReport.html
  PowerShell/ScubaGear/Sample-Reports/BaselineReports.html
Labels: enhancement

#1331 Improve nightly functional tests
  .github/actions/extract-email/action.yaml
  .github/actions/get-thumbprint/action.yaml
  .github/actions/import-pfx/action.yaml
  .github/actions/test-product/action.yaml
  .github/workflows/check_security.yaml
  .github/workflows/clear_cache.yaml
  .github/workflows/function_test_defender.yaml
  .github/workflows/function_test_entra.yaml
  .github/workflows/function_test_exchange.yaml
  .github/workflows/function_test_powerplatform.yaml
  .github/workflows/function_test_sharepoint.yaml
  .github/workflows/function_test_teams.yaml
  .github/workflows/publish_private_package.yaml
  .github/workflows/run_pipeline.yaml
  .github/workflows/run_workflow_pipeline.yaml
  .github/workflows/test_production_function.yaml
  Testing/Linting/MegaLinter/.checkov.yml
Labels: enhancement

#1382 Fix syntax error bug in nightly functional test workflow
  .github/workflows/test_production_function.yaml
Labels: bug

#1390 Fix schedule bug in nightly functional tests
  .github/workflows/test_production_function.yaml
Labels: bug
