Repository cisagov/ScubaGear, pull requests merged in 2024-11, with the labels that each got.

#1378 Add demo requirement to PR template pre-approval checklist
  .github/pull_request_template.md
Labels: enhancement

#1373 Update Module Version Bump Action to target the new documentation
  .github/workflows/run_module_version_bump.yml
  Testing/workflow/Set-ScubaGearModuleVersion/New-PRBody.Tests.ps1
  Testing/workflow/Set-ScubaGearModuleVersion/Set-ScubaGearVersionDoc.Tests.ps1
  Testing/workflow/Set-ScubaGearModuleVersion/Set-ScubaGearVersionManifest.Tests.ps1
  utils/workflow/Set-ScubaGearModuleVersion.psm1
Labels: bug

#1375 Change mechanism for calling PSSA
  .github/workflows/lint_powershell.yaml
  Testing/Linting/PSSA/.powershell-psscriptanalyzer.psd1
  utils/workflow/Invoke-PSSA.ps1
Labels: bug, enhancement

#1386 Correct Exchange unit tests that triggered long lines Regal warnings
  PowerShell/ScubaGear/Testing/Unit/Rego/EXO/EXOConfig_04_test.rego
Labels: bug, Testing

#1312 Adding Conditional Access Policy Implementation Instructions to AAD 1.1
  PowerShell/ScubaGear/baselines/aad.md
Labels: documentation

#1398 Update Front Matter across SCBs and specific language in the Defender SCB to match OCC approved language
  PowerShell/ScubaGear/baselines/aad.md
  PowerShell/ScubaGear/baselines/defender.md
  PowerShell/ScubaGear/baselines/exo.md
  PowerShell/ScubaGear/baselines/powerbi.md
  PowerShell/ScubaGear/baselines/powerplatform.md
  PowerShell/ScubaGear/baselines/removedpolicies.md
  PowerShell/ScubaGear/baselines/sharepoint.md
  PowerShell/ScubaGear/baselines/teams.md
Labels: baseline-document

#1413 Update incorrect hyperlinks in SCB markdown
  PowerShell/ScubaGear/baselines/aad.md
  PowerShell/ScubaGear/baselines/defender.md
Labels: baseline-document

#1401 Improve functional test notifications
  .github/workflows/function_test_defender.yaml
  .github/workflows/function_test_entra.yaml
  .github/workflows/function_test_exchange.yaml
  .github/workflows/function_test_powerplatform.yaml
  .github/workflows/function_test_sharepoint.yaml
  .github/workflows/function_test_teams.yaml
  PowerShell/ScubaGear/Sample-Config-Files/omit_policies.yaml
Labels: enhancement

#1406 improve performance of Defender query to count users without advanced auditing
  PowerShell/ScubaGear/Modules/Providers/ExportDefenderProvider.psm1
Labels: enhancement

#1412 Correct omission in documentation about importing module when downloading from GitHub
  docs/execution/execution.md
  docs/installation/github.md
Labels: documentation

#1428 Update schedule for functional test workflow
  .github/workflows/test_production_function.yaml
Labels: enhancement

#1423 Add service principal setup to functional testing documentation
  Testing/Readme.md
  Testing/docs/aad-service-principal.md
  Testing/docs/aad-tenant.md
Labels: documentation, enhancement

#1430 Convert workflow testing code to functions
  .github/workflows/publish_private_package.yaml
  Testing/workflow/Initialize-ScubaGearForTesting.Tests.ps1
  Testing/workflow/Install-SeleniumForTesting.Tests.ps1
  utils/workflow/Initialize-ScubaGearForTesting.ps1
  utils/workflow/Install-SeleniumForTesting.ps1
Labels: enhancement

#1426 Add the report UUID to the ScubaResults.json filename
  PowerShell/ScubaGear/Modules/Orchestrator.psm1
  PowerShell/ScubaGear/Modules/ScubaConfig/ScubaConfig.psm1
  PowerShell/ScubaGear/Sample-Reports/ScubaResults_21189b0e-f045-43ee-b9ba-653b32744e45.json
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Orchestrator/ConvertTo-ResultsCsv.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Orchestrator/Get-FullOutJsonName.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Orchestrator/Invoke-ProviderList.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Orchestrator/Invoke-ScubaCached.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Orchestrator/Merge-JsonOutput.Tests.ps1
  docs/configuration/parameters.md
  docs/execution/reports.md
Labels: enhancement
