Repository cisagov/ScubaGear, pull requests merged in 2024-01, with the labels that each got.

#741 Add project-specific pull request template
  .github/pull_request_template.md
Labels: infrastructure

#776 Fix debug preference error in OPA.ps1
  OPA.ps1
Labels: bug

#774 Enhance DoH Logic
  PowerShell/ScubaGear/Modules/Providers/ExportEXOProvider.psm1
Labels: enhancement

#789 Quick Fix of Invoke-RunCached
  PowerShell/ScubaGear/Modules/Orchestrator.psm1
Labels: bug

#793 Update YAML files to be compliant with linter
  .github/workflows/run_markdown_check.yaml
  .github/workflows/run_opa_tests.yaml
  .github/workflows/run_powershell_tests.yaml
  .github/workflows/run_publish_package.yaml
  .github/workflows/run_release.yaml
  .github/workflows/run_smoke_test.yaml
  .regal/config.yaml
  PowerShell/ScubaGear/Testing/Unit/PowerShell/ScubaConfig/config_test.yaml
  Testing/Functional/Products/TestConfigurations/defender/MS.DEFENDER.1.4v1/MatchedRecipientDomain.yaml
  Testing/Functional/Products/TestConfigurations/defender/MS.DEFENDER.1.4v1/MismatchedGroup.yaml
  Testing/Functional/Products/TestConfigurations/defender/MS.DEFENDER.1.4v1/MismatchedRecipientDomain.yaml
  Testing/Functional/Products/TestConfigurations/defender/MS.DEFENDER.1.4v1/MismatchedUser.yaml
  Testing/Functional/Products/TestConfigurations/defender/MS.DEFENDER.1.5v1/MatchedRecipientDomain.yaml
  Testing/Functional/Products/TestConfigurations/defender/MS.DEFENDER.1.5v1/MismatchedRecipientDomain.yaml
  Testing/Functional/Products/TestConfigurations/defender/MS.DEFENDER.2.1v1/MatchedUser.yaml
  Testing/Functional/Products/TestConfigurations/defender/MS.DEFENDER.2.1v1/MatchedWithMixedCase.yaml
  Testing/Functional/Products/TestConfigurations/defender/MS.DEFENDER.2.1v1/MismatchedUser.yaml
  Testing/Functional/Products/TestConfigurations/defender/MS.DEFENDER.2.2v1/AgencyDomainList.yaml
  Testing/Functional/Products/TestConfigurations/defender/MS.DEFENDER.2.3v1/PartnerDomainList.yaml
  Testing/Functional/Products/TestPlans/aad.g3.testplan.yaml
  Testing/Functional/Products/TestPlans/aad.g5.testplan.yaml
  Testing/Functional/Products/TestPlans/aad.testplan.yaml
  Testing/Functional/Products/TestPlans/defender.g3.testplan.yaml
  Testing/Functional/Products/TestPlans/defender.g5.testplan.yaml
  Testing/Functional/Products/TestPlans/defender.testplan.yaml
  Testing/Functional/Products/TestPlans/exo.testplan.yaml
  Testing/Functional/Products/TestPlans/powerplatform.testplan.yaml
  Testing/Functional/Products/TestPlans/sharepoint.pnp.testplan.yaml
  Testing/Functional/Products/TestPlans/sharepoint.spo.testplan.yaml
  Testing/Functional/Products/TestPlans/teams.gcc.testplan.yaml
  Testing/Functional/Products/TestPlans/teams.testplan.yaml
  sample-config-files/aad-config.yaml
  sample-config-files/defender-config.yaml
  sample-config-files/sample-config.yaml
Labels: enhancement

#708 Implement MS.AAD.6.1v1 check user password expiration
  PowerShell/ScubaGear/Modules/Providers/ExportAADProvider.psm1
  PowerShell/ScubaGear/Rego/AADConfig.rego
  PowerShell/ScubaGear/Rego/Utils/AAD.rego
  PowerShell/ScubaGear/Testing/Unit/Rego/AAD/AADConfig_06_test.rego
  Testing/Functional/Products/TestPlans/aad.testplan.yaml
Labels: enhancement

#809 Fix YAML and PowerShell linter warnings
  .github/workflows/run_linter_powershell.yaml
  .github/workflows/run_markdown_check.yaml
  Testing/Functional/Products/TestPlans/aad.testplan.yaml
  Testing/Linting/MegaLinter/.powershell-psscriptanalyzer.psd1
  sample-config-files/aad-config.yaml
Labels: bug

#795 Remove DoH Retry for NXDOMAIN
  PowerShell/ScubaGear/Modules/Providers/ExportEXOProvider.psm1
  PowerShell/ScubaGear/Modules/Providers/ProviderHelpers/CommandTracker.psm1
  PowerShell/ScubaGear/Rego/EXOConfig.rego
Labels: enhancement

#791 Refactor run release workflow to use azure key vault housed certificate
  .github/workflows/run_publish_package.yaml
  .github/workflows/run_release.yaml
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Orchestrator/Invoke-ReportCreation.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Orchestrator/Invoke-RunCached.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Orchestrator/Invoke-Scuba.Tests.ps1
  utils/DeployUtils.ps1
Labels: enhancement

#821 Insert Tags into Module for Discovery
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Utils/DeployUtils.Tests.ps1
  Testing/Functional/BuildTest/ModuleBuild.Tests.ps1
  utils/DeployUtils.ps1
Labels: enhancement

#799 Fix UpdateSelenium.ps1 script
  Testing/Functional/SmokeTest/UpdateSelenium.ps1
Labels: bug

#828 Improve nightly functional tests
  .github/workflows/run_functional_product_tests.yaml
  Testing/Functional/Products/Tests/CallProductTests.ps1
Labels: enhancement

#827 Updating the test orchestrator for custom implementation reporting strings
  PowerShell/ScubaGear/Rego/Utils/ReportDetails.rego
  Testing/Functional/Products/Products.Tests.ps1
Labels: bug, enhancement

#794 Add PIM for groups support to AAD provider
  PowerShell/ScubaGear/Modules/Connection/Connection.psm1
  PowerShell/ScubaGear/Modules/Providers/ExportAADProvider.psm1
  README.md
Labels: bug, enhancement

#822 Refactor escape sequence handling
  PowerShell/ScubaGear/Modules/Orchestrator.psm1
  PowerShell/ScubaGear/Modules/Providers/ExportAADProvider.psm1
  PowerShell/ScubaGear/Modules/Providers/ExportDefenderProvider.psm1
  PowerShell/ScubaGear/Modules/Providers/ExportEXOProvider.psm1
  PowerShell/ScubaGear/Modules/Providers/ExportPowerPlatformProvider.psm1
  PowerShell/ScubaGear/Modules/Providers/ExportSharePointProvider.psm1
  PowerShell/ScubaGear/Modules/Providers/ExportTeamsProvider.psm1
Labels: bug

#730 Fix report module to handle italics and multiline processing in policy description
  PowerShell/ScubaGear/Modules/CreateReport/CreateReport.psm1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/CreateReport/Resolve-HTMLMarkdown.Tests.ps1
  Testing/Unit/PowerShell/CreateReport/Resolve-HTMLMarkdown.Tests.ps1
  baselines/aad.md
  baselines/defender.md
Labels: bug

#849 Disable PnP PowerShell update banner
  PowerShell/ScubaGear/Modules/Connection/Connection.psm1
Labels: bug

#761 Allow config file to override command line parameters
  PowerShell/ScubaGear/Modules/Orchestrator.psm1
  PowerShell/ScubaGear/Modules/ScubaConfig/ScubaConfig.psm1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Orchestrator/Invoke-ScubaConfig.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Orchestrator/orchestrator_config_test.yaml
  README.md
Labels: bug, enhancement

#848 Add terms of use handling to CAP table
  PowerShell/ScubaGear/Modules/Providers/ProviderHelpers/AADConditionalAccessHelper.psm1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/AADProvider/Export-Caps.Tests.ps1
Labels: bug

#858 Update test plan for Teams product to fix issues observed during Nightly-Products-Functional-Test workflow
  Testing/Functional/Products/TestPlans/teams.testplan.yaml
Labels: bug, Testing

#812 Add configuration file documentation to README
  README.md
  sample-config-files/basic_config.yaml
  sample-config-files/creds_config.yaml
  sample-config-files/full_config.yaml
  sample-config-files/typical_config.yaml
Labels: documentation

#864 Fix MS.EXO.17 implementation instruction policy ID refs
  PowerShell/ScubaGear/baselines/exo.md
Labels: bug, baseline-document

#866 HTML Report Links to Version Baselines
  PowerShell/ScubaGear/Modules/CreateReport/CreateReport.psm1
  PowerShell/ScubaGear/Modules/CreateReport/IndividualReport/IndividualReport.html
  PowerShell/ScubaGear/Modules/CreateReport/ParentReport/ParentReport.html
  PowerShell/ScubaGear/Modules/Orchestrator.psm1
Labels: bug

#872 Update AAD baseline to include PIM for Groups (the return of)
  PowerShell/ScubaGear/baselines/aad.md
Labels: documentation

#874 Update release to use production code signing certificate
  .github/workflows/run_release.yaml
Labels: enhancement

#853 Version bump to 1.1.0
  PowerShell/ScubaGear/ScubaGear.psd1
  README.md
Labels: version bump

#881 Add Unblock-File workaround for execution warnings
  README.md
Labels: documentation, enhancement
