Repository cisagov/ScubaGear, pull requests merged in 2024-03, with the labels that each got.

#926 add PIM for Groups to AAD baseline instructions for 7.6 through 7.9
  PowerShell/ScubaGear/baselines/aad.md
Labels: baseline-document

#939 Revise M.S.EXO.5.1 to remove exceptional note
  PowerShell/ScubaGear/baselines/exo.md
Labels: baseline-document

#953 Aligned baseline policies criticality between code and document
  PowerShell/ScubaGear/Rego/SharepointConfig.rego
  PowerShell/ScubaGear/Rego/TeamsConfig.rego
Labels: bug

#890 Unit Test should not depend on external modules
  .github/workflows/run_powershell_tests.yaml
  PowerShell/ScubaGear/Modules/ScubaConfig/ScubaConfig.psm1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Connection/Connect-DefenderHelper.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Connection/Connect-ExoHelper.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Connection/Connect-Tenant.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Connection/Disconnect-SCuBATenant.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Orchestrator/Connect-Tenant.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Orchestrator/Invoke-ScubaConfig.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/AADProvider/Export-AADProvider.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/AADProvider/Get-AADTenantDetail.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/AADProvider/Get-PrivilegedRole.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/AADProvider/Get-PrivilegedUser.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/DefenderProvider/Export-DefenderProvider.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/EXOProvider/Export-EXOProvider.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/EXOProvider/Get-EXOTenantDetail.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/PowerPlatformProvider/Export-PowerPlatformProvider.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/PowerPlatformProvider/Get-PowerPlatformTenantDetail.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/TeamsProvider/Get-TeamsTenantDetail.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/RunRego/Run-Rego.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/ScubaConfig/ScubaConfigDelete.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/ScubaConfig/ScubaConfigJson.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/ScubaConfig/ScubaConfigJsonMissingDefaults.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/ScubaConfig/ScubaConfigLoadConfig.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/ScubaConfig/ScubaConfigYaml.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/ScubaConfig/config_test.json
  PowerShell/ScubaGear/Testing/Unit/PowerShell/ScubaConfig/config_test.yaml
  PowerShell/ScubaGear/Testing/Unit/PowerShell/ScubaConfig/config_test_load_config1.json
  PowerShell/ScubaGear/Testing/Unit/PowerShell/ScubaConfig/config_test_load_config2.json
  PowerShell/ScubaGear/Testing/Unit/PowerShell/ScubaConfig/config_test_missing_defaults.json
Labels: Testing

#966 Re-pin MS Graph to latest major/minor (i.e., 2.15.xx) version
  PowerShell/ScubaGear/RequiredVersions.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Connection/Connect-Tenant.Tests.ps1
Labels: enhancement

#974 Specify Repo to query in Public Private Package workflow
  .github/workflows/publish_package.yaml
Labels: bug

#956 Remove orphan PowerShell unit test
  Testing/Unit/PowerShell/CreateReport/Resolve-HTMLMarkdown.Tests.ps1
Labels: bug

#905 Finish nightly functional tests
  .github/workflows/test_production_function.yaml
  PowerShell/ScubaGear/Dependencies.ps1
  PowerShell/ScubaGear/Modules/Support/Support.psm1
Labels: enhancement

#970 Create Json Output
  PowerShell/ScubaGear/Modules/CreateReport/CreateReport.psm1
  PowerShell/ScubaGear/Modules/Orchestrator.psm1
  PowerShell/ScubaGear/Modules/ScubaConfig/ScubaConfig.psm1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Orchestrator/Invoke-RunCached.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Orchestrator/Invoke-Scuba.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Orchestrator/Invoke-ScubaConfig.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Orchestrator/Merge-JsonOutput.Tests.ps1
  README.md
Labels: enhancement

#962 Add scope attributes to tables in HTML Report
  PowerShell/ScubaGear/Modules/CreateReport/CreateReport.psm1
  PowerShell/ScubaGear/Modules/CreateReport/scripts/ParentReport.js
  PowerShell/ScubaGear/Modules/CreateReport/scripts/main.js
  PowerShell/ScubaGear/Modules/CreateReport/scripts/utils.js
  Testing/Functional/SmokeTest/SmokeTest002.Tests.ps1
Labels: enhancement

#945 Add code to AAD provider and REGO for 7.6 through 7.9 to support PIM for Groups
  PowerShell/ScubaGear/Modules/Connection/Connection.psm1
  PowerShell/ScubaGear/Modules/Providers/ExportAADProvider.psm1
  PowerShell/ScubaGear/Rego/AADConfig.rego
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Connection/Connect-Tenant.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/Rego/AAD/AADConfig_07_test.rego
  README.md
  Testing/Functional/Products/TestPlans/aad.g5.testplan.yaml
Labels: enhancement

#1011 (New) Add Licensing Information to AAD Report
  PowerShell/ScubaGear/Modules/CreateReport/CreateReport.psm1
  PowerShell/ScubaGear/Modules/CreateReport/IndividualReport/IndividualReport.html
  PowerShell/ScubaGear/Modules/CreateReport/scripts/main.js
  PowerShell/ScubaGear/Modules/Providers/ExportAADProvider.psm1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/CreateReport/CreateReportStubs/ProviderSettingsExport.json
  Testing/Functional/Products/Products.Tests.ps1
  Testing/Functional/SmokeTest/SmokeTest002.Tests.ps1
Labels: enhancement

#1009 Add a UTC timestamp to the Provider JSON
  PowerShell/ScubaGear/Modules/Orchestrator.psm1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Orchestrator/Merge-JsonOutput.Tests.ps1
Labels: enhancement

#1001 Add config file for GitHub Pages
  _config.yml
Labels: enhancement

#989 Create a workflow for bumping the ScubaGear module version
  .github/workflows/run_module_version_bump.yml
Labels: enhancement

#1019 Fix the Handful of AAD unit tests that are broken
  PowerShell/ScubaGear/Testing/Unit/Rego/AAD/AADConfig_07_test.rego
Labels: enhancement

#996 Remove default variables from Defender test configs
  Testing/Functional/Products/TestConfigurations/defender/MS.DEFENDER.1.4v1/MatchedRecipientDomain.yaml
  Testing/Functional/Products/TestConfigurations/defender/MS.DEFENDER.1.4v1/MismatchedGroup.yaml
  Testing/Functional/Products/TestConfigurations/defender/MS.DEFENDER.1.4v1/MismatchedRecipientDomain.yaml
  Testing/Functional/Products/TestConfigurations/defender/MS.DEFENDER.1.4v1/MismatchedUser.yaml
  Testing/Functional/Products/TestConfigurations/defender/MS.DEFENDER.1.5v1/MatchedRecipientDomain.yaml
  Testing/Functional/Products/TestConfigurations/defender/MS.DEFENDER.1.5v1/MismatchedRecipientDomain.yaml
  Testing/Functional/Products/TestConfigurations/defender/MS.DEFENDER.2.1v1/MatchedUser.yaml
  Testing/Functional/Products/TestConfigurations/defender/MS.DEFENDER.2.1v1/MatchedWithMixedCase.yaml
  Testing/Functional/Products/TestConfigurations/defender/MS.DEFENDER.2.1v1/MismatchedUser.yaml
  Testing/Functional/Products/TestConfigurations/defender/MS.DEFENDER.2.2v1/AgencyDomainList.yaml
  Testing/Functional/Products/TestConfigurations/defender/MS.DEFENDER.2.3v1/PartnerDomainList.yaml
Labels: bug, Testing

#1031 Uncenter the text in the HTML report
  PowerShell/ScubaGear/Modules/CreateReport/CreateReport.psm1
Labels: bug

#984 Add option to generate a config file template
  PowerShell/ScubaGear/Modules/Support/Support.psm1
  PowerShell/ScubaGear/ScubaGear.psd1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/CreateReport/Import-SecureBaseline.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/CreateReport/New-Report.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Support/New-Config.Tests.ps1
  README.md
Labels: enhancement
