Repository cisagov/ScubaGear, pull requests merged in 2025-07, with the labels that each got.

#1723 Fix PowerPlatform DLP policy bug and remove Get-TenantDetailsFromGraph commandlet
  PowerShell/ScubaGear/Modules/Connection/Connection.psm1
  PowerShell/ScubaGear/Modules/Providers/ExportPowerPlatformProvider.psm1
  PowerShell/ScubaGear/Rego/PowerPlatformConfig.rego
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/PowerPlatformProvider/Export-PowerPlatformProvider.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/Rego/PowerPlatform/PowerPlatformBaseConfig.rego
  PowerShell/ScubaGear/Testing/Unit/Rego/PowerPlatform/PowerPlatformConfig_02_test.rego
  Testing/Functional/Products/TestPlans/powerplatform.testplan.yaml
Labels: bug

#1713 Remove dependency of remaining Microsoft Graph modules
  PowerShell/ScubaGear/Modules/Connection/Connection.psm1
  PowerShell/ScubaGear/Modules/Orchestrator.psm1
  PowerShell/ScubaGear/Modules/Permissions/ScubaGearPermissions.json
  PowerShell/ScubaGear/Modules/Providers/ExportAADProvider.psm1
  PowerShell/ScubaGear/Modules/Providers/ExportSharePointProvider.psm1
  PowerShell/ScubaGear/Modules/Providers/ProviderHelpers/AADRiskyPermissionsHelper.psm1
  PowerShell/ScubaGear/Modules/Providers/ProviderHelpers/CommandTracker.psm1
  PowerShell/ScubaGear/RequiredVersions.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Connection/Connect-Tenant.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/AADProvider/AADRiskyPermissionsHelper/Format-RiskyApplications.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/AADProvider/AADRiskyPermissionsHelper/Format-RiskyThirdPartyServicePrincipals.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/AADProvider/AADRiskyPermissionsHelper/Get-ApplicationsWithRiskyPermissions.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/AADProvider/AADRiskyPermissionsHelper/Get-ServicePrincipalsWithRiskyPermissions.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/AADProvider/Get-AADTenantDetail.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/AADProvider/Invoke-GraphDirectly.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/AADProvider/LoadObjectDataIntoPrivilegedUserHashtable.Tests.ps1
  utils/UninstallModules.ps1
Labels: enhancement

#1738 Add capability to annotate controls
  PowerShell/ScubaGear/Modules/CreateReport/CreateReport.psm1
  PowerShell/ScubaGear/Modules/CreateReport/scripts/main.js
  PowerShell/ScubaGear/Modules/CreateReport/styles/ParentReportStyle.css
  PowerShell/ScubaGear/Modules/CreateReport/styles/main.css
  PowerShell/ScubaGear/Modules/Orchestrator.psm1
  PowerShell/ScubaGear/Modules/ScubaConfig/ScubaConfig.psm1
  PowerShell/ScubaGear/Sample-Config-Files/annotate_policies.yaml
  PowerShell/ScubaGear/Sample-Config-Files/omit_policies.yaml
  PowerShell/ScubaGear/Sample-Config-Files/scuba_compliance.yaml
  PowerShell/ScubaGear/Testing/Unit/PowerShell/CreateReport/Add-Annotation.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/CreateReport/Get-OmissionState.Tests.ps1
  docs/configuration/configuration.md
  docs/configuration/parameters.md
Labels: enhancement

#1747 Update sample reports for v1.6.0
  PowerShell/ScubaGear/Sample-Reports/ActionPlan.csv
  PowerShell/ScubaGear/Sample-Reports/BaselineReports.html
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/AADReport.html
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/AADReport.json
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/DefenderReport.html
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/DefenderReport.json
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/EXOReport.html
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/EXOReport.json
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/PowerPlatformReport.html
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/PowerPlatformReport.json
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/SharePointReport.html
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/SharePointReport.json
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/TeamsReport.html
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/TeamsReport.json
  PowerShell/ScubaGear/Sample-Reports/ProviderSettingsExport.json
  PowerShell/ScubaGear/Sample-Reports/ScubaResults.csv
  PowerShell/ScubaGear/Sample-Reports/ScubaResults_0d275954-350e-4a22.json
  PowerShell/ScubaGear/Sample-Reports/TestResults.json
Labels: documentation

#1744 Update AAD baselines to reflect Entra Portal changes
  PowerShell/ScubaGear/baselines/aad.md
Labels: baseline-document

#1762 Fix bug when tenant has no conditional access policies
  PowerShell/ScubaGear/Modules/CreateReport/scripts/main.js
  PowerShell/ScubaGear/Modules/CreateReport/styles/main.css
  PowerShell/ScubaGear/Modules/Providers/ProviderHelpers/AADConditionalAccessHelper.psm1
Labels: bug

#1766 Add Authentication Strength Capability for AAD 3.2v1
  PowerShell/ScubaGear/Rego/AADConfig.rego
  PowerShell/ScubaGear/Rego/Utils/AAD.rego
  PowerShell/ScubaGear/Testing/Unit/Rego/AAD/AADConfig_03_test.rego
  Testing/Functional/Products/TestPlans/aad.testplan.yaml
Labels: bug, public-reported
