Repository cisagov/ScubaGear, pull requests merged in 2025-01, with the labels that each got.

#1481 Remove reference to removed VersionCheckFile
  PowerShell/ScubaGear/CheckVersion.ps1
Labels: bug

#1472 Remove unused clear cache workflow
  .github/workflows/clear_cache.yaml
Labels: enhancement

#1497 Update readme with new ScubaGear graphic
  README.md
  docs/images/SCuBA GitHub Graphic v6-05.png
  docs/images/cisa.png
Labels: documentation, baseline-document
