Repository cisagov/ScubaGear, pull requests merged in 2025-02, with the labels that each got.

#1515 Add Defender configuration options documentation
  docs/configuration/configuration.md
Labels: documentation, enhancement

#1528 Remove outdated parameters from sample config files
  PowerShell/ScubaGear/Sample-Config-Files/aad_config.yaml
  PowerShell/ScubaGear/Sample-Config-Files/defender_config.yaml
  PowerShell/ScubaGear/Sample-Config-Files/full_config.yaml
  PowerShell/ScubaGear/Sample-Config-Files/omit_policies.yaml
  PowerShell/ScubaGear/Sample-Config-Files/sample_config.json
  PowerShell/ScubaGear/Sample-Config-Files/sample_config.yaml
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Support/Copy-ScubaSampleConfigFile.Tests.ps1
  Testing/Functional/SmokeTest/SmokeTest001.Tests.ps1
  docs/configuration/configuration.md
Labels: bug, documentation

#1529 Revise Entra report header with new exclusion info and documentation name
  PowerShell/ScubaGear/Modules/CreateReport/CreateReport.psm1
  docs/configuration/configuration.md
Labels: documentation

#1530 Updated Microsoft.PowerApps.Administration.PowerShell min/max versions
  PowerShell/ScubaGear/RequiredVersions.ps1
Labels: upstream update

#1521 Write unit tests for build and sign release
  .github/workflows/build_sign_release.yaml
  .github/workflows/publish_private_package.yaml
  .github/workflows/publish_public_package.yaml
  Testing/workflow/Build-SignRelease.Tests.ps1
  Testing/workflow/Install-AzureSignTool.Tests.ps1
  utils/workflow/Build-SignRelease.ps1
  utils/workflow/Install-AzureSignTool.ps1
  utils/workflow/Publish-ScubaGear.ps1
Labels: enhancement, infrastructure

#1549 Add rego checks to test AAD policy with Authenticator
  PowerShell/ScubaGear/Rego/AADConfig.rego
  PowerShell/ScubaGear/Testing/Unit/Rego/AAD/AADConfig_03_test.rego
  Testing/Functional/Products/TestPlans/aad.testplan.yaml
Labels: bug, public-reported

#1547 Config file error message for duplicate keys fixed and improved
  PowerShell/ScubaGear/Modules/ScubaConfig/ScubaConfig.psm1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/ScubaConfig/MockLoadConfig.yaml
  PowerShell/ScubaGear/Testing/Unit/PowerShell/ScubaConfig/ScubaConfigLoadConfig.Tests.ps1
Labels: enhancement

#1462 Add high risk application/service principal permissions into ScubaResults.json
  PowerShell/ScubaGear/Modules/Permissions/RiskyPermissions.json
  PowerShell/ScubaGear/Modules/Providers/ExportAADProvider.psm1
  PowerShell/ScubaGear/Modules/Providers/ProviderHelpers/AADRiskyPermissionsHelper.psm1
  PowerShell/ScubaGear/Modules/Providers/ProviderHelpers/CommandTracker.psm1
  PowerShell/ScubaGear/RequiredVersions.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/AADProvider/AADRiskyPermissionsHelper/Format-Credentials.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/AADProvider/AADRiskyPermissionsHelper/Format-RiskyApplications.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/AADProvider/AADRiskyPermissionsHelper/Format-RiskyPermission.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/AADProvider/AADRiskyPermissionsHelper/Format-ThirdPartyRiskyServicePrincipals.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/AADProvider/AADRiskyPermissionsHelper/Get-ApplicationsWithRiskyPermissions.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/AADProvider/AADRiskyPermissionsHelper/Get-ServicePrincipalsWithRiskyPermissions.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/AADProvider/AADRiskyPermissionsHelper/Merge-Credentials.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/AADProvider/Export-AADProvider.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/AADProvider/RiskyPermissionsSnippets/MockApplicationPermissions.json
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/AADProvider/RiskyPermissionsSnippets/MockApplications.json
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/AADProvider/RiskyPermissionsSnippets/MockFederatedCredentials.json
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/AADProvider/RiskyPermissionsSnippets/MockSafePermissions.json
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/AADProvider/RiskyPermissionsSnippets/MockServicePrincipalAppRoleAssignments.json
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/AADProvider/RiskyPermissionsSnippets/MockServicePrincipals.json
Labels: enhancement

#1537 Add Rego checks for Application & role Exclusions and be consistent across Conditional Access Policies
  PowerShell/ScubaGear/Rego/AADConfig.rego
  PowerShell/ScubaGear/Rego/Utils/AAD.rego
  PowerShell/ScubaGear/Testing/Unit/Rego/AAD/AADBaseConfig.rego
  PowerShell/ScubaGear/Testing/Unit/Rego/AAD/AADConfig_01_test.rego
  PowerShell/ScubaGear/Testing/Unit/Rego/AAD/AADConfig_02_test.rego
  PowerShell/ScubaGear/Testing/Unit/Rego/AAD/AADConfig_03_test.rego
Labels: bug

#1467 Add privileged service principals table to AAD report
  PowerShell/ScubaGear/Modules/CreateReport/CreateReport.psm1
  PowerShell/ScubaGear/Modules/CreateReport/IndividualReport/IndividualReport.html
  PowerShell/ScubaGear/Modules/Providers/ExportAADProvider.psm1
  PowerShell/ScubaGear/RequiredVersions.ps1
  Testing/Functional/SmokeTest/SmokeTest002.Tests.ps1
Labels: enhancement

#1557 Update ScubaGear authentication documentation for additional GCC High, Defender, and SharePoint details
  docs/prerequisites/interactive.md
  docs/prerequisites/noninteractive.md
Labels: documentation, enhancement

#1565 Update AAD functional tests for service principal table
  Testing/Functional/Products/Products.Tests.ps1
Labels: bug, Testing

#1566 Update sample reports for 1.5.0
  PowerShell/ScubaGear/Sample-Reports/ActionPlan.csv
  PowerShell/ScubaGear/Sample-Reports/BaselineReports.html
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/AADReport.html
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/AADReport.json
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/DefenderReport.html
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/DefenderReport.json
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/EXOReport.html
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/EXOReport.json
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/PowerPlatformReport.html
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/PowerPlatformReport.json
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/SharePointReport.html
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/SharePointReport.json
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/TeamsReport.html
  PowerShell/ScubaGear/Sample-Reports/IndividualReports/TeamsReport.json
  PowerShell/ScubaGear/Sample-Reports/ProviderSettingsExport.json
  PowerShell/ScubaGear/Sample-Reports/ScubaResults.csv
  PowerShell/ScubaGear/Sample-Reports/ScubaResults_550fbc57-f602-4b40.json
  PowerShell/ScubaGear/Sample-Reports/TestResults.json
Labels: documentation

#1590 Remove duplicate ModuleName "Microsoft.Graph.Beta.Applications" from RequiredVersions.ps1
  PowerShell/ScubaGear/RequiredVersions.ps1
Labels: bug

#1563 Ignore coexistence domain for the DMARC controls
  PowerShell/ScubaGear/Modules/Providers/ExportEXOProvider.psm1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/EXOProvider/Get-ScubaDmarcRecord.Tests.ps1
Labels: bug

#1576 Update README.md with relative rather than absolute URL for ScubaGear logo
  README.md
Labels: documentation
