Repository cisagov/ScubaGear, pull requests merged in 2025-08, with the labels that each got.

#1771 Updated manual download OPA pointer when OPA installation fails during initialization.
  PowerShell/ScubaGear/Modules/Support/Support.psm1
  utils/workflow/Update-Opa.ps1
Labels: documentation

#1740 Update write permissions for the PS version bump workflow
  .github/workflows/ps_dependencies_requiredversionsfile.yaml
Labels: bug

#1779 Add full config file to include all possible parameters
  PowerShell/ScubaGear/Modules/Orchestrator.psm1
  PowerShell/ScubaGear/Sample-Config-Files/aad_config.yaml
  PowerShell/ScubaGear/Sample-Config-Files/annotate_policies.yaml
  PowerShell/ScubaGear/Sample-Config-Files/basic_config.yaml
  PowerShell/ScubaGear/Sample-Config-Files/creds_config.yaml
  PowerShell/ScubaGear/Sample-Config-Files/defender_config.yaml
  PowerShell/ScubaGear/Sample-Config-Files/exo_config.yaml
  PowerShell/ScubaGear/Sample-Config-Files/full_config.yaml
  PowerShell/ScubaGear/Sample-Config-Files/omit_policies.yaml
  PowerShell/ScubaGear/Sample-Config-Files/sample_config.yaml
  PowerShell/ScubaGear/Sample-Config-Files/typical_config.yaml
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Support/Copy-ScubaSampleConfigFile.Tests.ps1
  Testing/Functional/SmokeTest/SmokeTest001.Tests.ps1
  docs/configuration/configuration.md
Labels: enhancement

#1778 Update policy migration state (AAD 3.4)
  PowerShell/ScubaGear/Rego/AADConfig.rego
  PowerShell/ScubaGear/Testing/Unit/Rego/AAD/AADConfig_03_test.rego
  Testing/Functional/Products/TestPlans/aad.testplan.yaml
Labels: enhancement

#1790 Update test plan from MS.TEAMS.1.5v2 to MS.TEAMS.1.5v1 to fix Teams functional test failures.
  Testing/Functional/Products/TestPlans/teams.testplan.yaml
Labels: bug

#1786 Enhance scubagear documentation and sample configurations
  README.md
  docs/configuration/configuration.md
  docs/configuration/parameters.md
  docs/images/opa_version.png
  docs/prerequisites/dependencies.md
Labels: documentation
