Repository cisagov/ScubaGear, pull requests merged in 2025-06, with the labels that each got.

#1656 Add NIST SP 800-53 Mappings to the Baselines
  PowerShell/ScubaGear/baselines/aad.md
  PowerShell/ScubaGear/baselines/defender.md
  PowerShell/ScubaGear/baselines/exo.md
  PowerShell/ScubaGear/baselines/powerbi.md
  PowerShell/ScubaGear/baselines/powerplatform.md
  PowerShell/ScubaGear/baselines/sharepoint.md
  PowerShell/ScubaGear/baselines/teams.md
  PowerShell/ScubaGear/mappings/scuba-to-nist-sp-800-53-r5-fedramp-high.csv
  README.md
  docs/misc/mappings.md
Labels: baseline-document

#1684 Issue 1096: bump module dependencies
  .github/workflows/ps_dependencies_requiredversionsfile.yaml
  utils/workflow/BumpPsDependencies.ps1
Labels: enhancement

#1682 Add fix for invalid JSON primitive issues related to risky service principals
  PowerShell/ScubaGear/Modules/Permissions/ScubaGearPermissions.json
  PowerShell/ScubaGear/Modules/Providers/ExportAADProvider.psm1
  PowerShell/ScubaGear/Modules/Providers/ProviderHelpers/AADRiskyPermissionsHelper.psm1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/AADProvider/AADRiskyPermissionsHelper/Format-Permission.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/AADProvider/AADRiskyPermissionsHelper/Format-RiskyApplications.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/AADProvider/AADRiskyPermissionsHelper/Format-RiskyThirdPartyServicePrincipals.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/AADProvider/AADRiskyPermissionsHelper/Get-ApplicationsWithRiskyPermissions.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/AADProvider/AADRiskyPermissionsHelper/Get-ServicePrincipalsWithRiskyPermissions.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/AADProvider/Export-AADProvider.Tests.ps1
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/AADProvider/RiskyPermissionsSnippets/MockApplicationPermissions.json
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/AADProvider/RiskyPermissionsSnippets/MockResourcePermissionCache.json
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/AADProvider/RiskyPermissionsSnippets/MockServicePrincipalAppRoleAssignments.json
  PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/AADProvider/RiskyPermissionsSnippets/MockServicePrincipals.json
Labels: bug
